// rawfiles/src/views/layouts/horizontal/index.tsx

import {Fragment, useEffect} from "react";
import {Alert, Col, Container, Row} from "react-bootstrap";
import PageBreadcrumb from "@/components/PageBreadcrumb";
import {useLayoutContext} from "@/context/useLayoutContext";
import {TbInfoCircle} from "react-icons/tb";

const Page = () => {

    const {changeOrientation, reset} = useLayoutContext()

    useEffect(() => {
        changeOrientation('horizontal')

        return () => reset()
    }, [])

    return (
        <Fragment>

            <Container fluid>
                <PageBreadcrumb title="Horizontal"/>
            </Container>

            <Container fluid="xl">
                <Row>
                    <Col sm={12}>
                        <Alert variant="info"
                               className="alert-bordered border-start border-info d-flex align-items-start gap-2">
                            <TbInfoCircle className="fs-xxl"/>
                            <div>
                                To enable the horizontal layout,
                                use <code> changeOrientation('horizontal')</code> from
                                the <code>LayoutContext</code>. Or you can just wrap your page
                                with <code>HorizontalLayout</code>.
                            </div>
                        </Alert>
                    </Col>
                </Row>
            </Container>
        </Fragment>
    )
}

export default Page

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/layouts/horizontal/horizontal.component.ts
import {Component, inject, OnDestroy, OnInit} from '@angular/core';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {NgIcon} from '@ng-icons/core';
import {NgbAlert} from '@ng-bootstrap/ng-bootstrap';
import {PageTitleComponent} from '@app/components/page-title.component';
import {NavigationEnd, Router} from '@angular/router';
import {filter} from 'rxjs';

@Component({
    selector: 'app-horizontal',
    imports: [
        NgIcon,
        NgbAlert,
        PageTitleComponent
    ],
    templateUrl: './horizontal.component.html',
})
export class HorizontalComponent implements OnInit, OnDestroy {

    layout = inject(LayoutStoreService)
    router = inject(Router)

    ngOnInit() {
        this.layout.setLayoutOrientation('horizontal')
    }

    ngOnDestroy() {
        const sub = this.router.events
            .pipe(filter(event => event instanceof NavigationEnd))
            .subscribe(() => {
                this.layout.setLayoutOrientation('vertical');
                this.layout.setSidenavSize('default');
                sub.unsubscribe();
            });
    }
}

<div class="container-fluid">
    <app-page-title title="Horizontal"/>

    <div class="row">
        <div class="col-12">
            <ngb-alert type="info" class="alert-bordered border-start border-info d-flex align-items-start gap-2">
                <ng-icon name="tablerInfoCircle" class="fs-xxl"/>
                <div>
                    To enable the horizontal layout, use
                    <code>LayoutStoreService</code> with
                    <code>setLayoutOrientation('horizontal')</code> or you can directly wrap your page with <code>HorizontalLayoutComponent</code>.
                </div>
            </ngb-alert>
        </div>
    </div>
</div>
