// src_old/views/auth/auth-2/delete-account/index.tsx
import { Button, Card, CardBody, Col, Container, Row } from 'react-bootstrap';
import AppLogo from '@/components/AppLogo';

import { author, currentYear } from '@/helpers';

import deleteIcon from '@/assets/images/delete.png';

const DeleteAccount = () => {
    return (
        <div className="auth-box d-flex align-items-center">
            <Container fluid className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <CardBody>
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                        </div>

                                        <div className="mb-4">
                                            <div className="avatar-xxl mx-auto mt-2">
                                                <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                                    <img src={deleteIcon} alt="delete icon" height={64} />
                                                </div>
                                            </div>
                                        </div>

                                        <h4 className="fw-bold text-center mb-3">Account Deactivated</h4>
                                        <p className="text-muted text-center mb-4">
                                            Your account is currently inactive. Reactivate now to regain access to all features and opportunities.
                                        </p>

                                        <div className="d-grid">
                                            <Button type="button" variant="primary" className="fw-semibold py-2">
                                                Reactivate Now
                                            </Button>
                                        </div>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
                                        </p>
                                    </CardBody>
                                </Col>

                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">

                                        </div>
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </div>
    );
};

export default DeleteAccount;

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/delete-account/delete-account.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-delete-account',
    host: { 'data-component-id': 'auth2-delete-account' },
    imports: [RouterLink],
    templateUrl: './delete-account.component.html',
    styles: ``
})
export class DeleteAccountComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                </div>

                                <div class="mb-4">
                                    <div class="avatar-xxl mx-auto mt-2">
                                        <div
                                            class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                            <img src="assets/images/delete.png" alt="dark logo" height="64">
                                        </div>
                                    </div>
                                </div>

                                <h4 class="fw-bold text-center mb-3">Account Deactivated</h4>
                                <p class="text-muted text-center mb-4">Your account is currently inactive. Reactivate
                                    now to regain access to all features and opportunities.</p>

                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary fw-semibold py-2">Reactivate
                                        Now</button>
                                </div>


                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
