// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/topbar/components/mega-menu/mega-menu.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterLink} from '@angular/router';
import {NgIcon} from '@ng-icons/core';
import {NgbDropdown, NgbDropdownMenu, NgbDropdownToggle} from '@ng-bootstrap/ng-bootstrap';

type MegaMenuType = {
    title: string;
    links: {
        label: string;
        url: string;
    }[];
};

@Component({
    selector: 'app-mega-menu',
    imports: [CommonModule, RouterLink, NgIcon, NgbDropdown, NgbDropdownToggle, NgbDropdownMenu],
    templateUrl: './mega-menu.component.html',
})
export class MegaMenuComponent {

    megaMenuItems: MegaMenuType[] = [
        {
            title: 'Dashboard & Analytics',
            links: [
                {label: 'Sales Dashboard', url: '#;'},
                {label: 'Marketing Dashboard', url: '#;'},
                {label: 'Finance Overview', url: '#;'},
                {label: 'User Analytics', url: '#;'},
                {label: 'Traffic Insights', url: '#;'},
                {label: 'Performance Metrics', url: '#;'},
                {label: 'Conversion Tracking', url: '#;'}
            ]
        },
        {
            title: 'Project Management',
            links: [
                {label: 'Task Overview', url: '#;'},
                {label: 'Kanban Board', url: '#;'},
                {label: 'Gantt Chart', url: '#;'},
                {label: 'Team Collaboration', url: '#;'},
                {label: 'Project Milestones', url: '#;'},
                {label: 'Workflow Automation', url: '#;'},
                {label: 'Timesheets & Reports', url: '#;'}
            ]
        },
        {
            title: 'User Management',
            links: [
                {label: 'User Profiles', url: '#;'},
                {label: 'Access Control', url: '#;'},
                {label: 'Role Permissions', url: '#;'},
                {label: 'Activity Logs', url: '#;'},
                {label: 'Security Settings', url: '#;'},
                {label: 'User Groups', url: '#;'},
                {label: 'Authentication & Login', url: '#;'}
            ]
        }
    ];

}

<div class="topbar-item d-none d-md-flex">
    <div ngbDropdown class="dropdown">
        <button ngbDropdownToggle class="topbar-link btn fw-medium btn-link dropdown-toggle drop-arrow-none">
            Boom Boom! 😍
            <ng-icon name="tablerChevronDown" class="ms-1"/>
        </button>
        <div ngbDropdownMenu class="dropdown-menu dropdown-menu-xxl p-0">
            <div class="h-100" style="max-height: 380px;" data-simplebar>
                <div class="row g-0">
                    <div class="col-12">
                        <div class="p-3 text-center bg-light bg-opacity-50">
                            <h4 class="mb-0 fs-lg fw-semibold">Welcome to <span
                                class="text-primary">INSPINIA+</span> Admin Theme.</h4>
                        </div>
                    </div>
                </div>
                <div class="row g-0">
                    <div *ngFor="let item of megaMenuItems" class="col-md-4">
                        <div class="p-3">
                            <h5 class="mb-2 fw-semibold fs-sm dropdown-header">{{ item.title }}</h5>
                            <ul class="list-unstyled megamenu-list">
                                <li *ngFor="let link of item.links">
                                    <a [routerLink]="link.url" class="dropdown-item">{{ link.label }}</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// src/layouts/components/topbar/components/MegaMenu.tsx
import {Col, Dropdown, DropdownMenu, DropdownToggle, Row} from "react-bootstrap";
import {TbChevronDown} from "react-icons/tb";
import SimpleBar from "simplebar-react";
import { Link } from "react-router";

type MegaMenuType = {
    title: string;
    links: {
        label: string;
        url: string;
    }[];
};

const megaMenuItems: MegaMenuType[] = [
    {
        title: 'Dashboard & Analytics',
        links: [
            {label: 'Sales Dashboard', url: '#;'},
            {label: 'Marketing Dashboard', url: '#;'},
            {label: 'Finance Overview', url: '#;'},
            {label: 'User Analytics', url: '#;'},
            {label: 'Traffic Insights', url: '#;'},
            {label: 'Performance Metrics', url: '#;'},
            {label: 'Conversion Tracking', url: '#;'}
        ]
    },
    {
        title: 'Project Management',
        links: [
            {label: 'Task Overview', url: '#;'},
            {label: 'Kanban Board', url: '#;'},
            {label: 'Gantt Chart', url: '#;'},
            {label: 'Team Collaboration', url: '#;'},
            {label: 'Project Milestones', url: '#;'},
            {label: 'Workflow Automation', url: '#;'},
            {label: 'Timesheets & Reports', url: '#;'}
        ]
    },
    {
        title: 'User Management',
        links: [
            {label: 'User Profiles', url: '#;'},
            {label: 'Access Control', url: '#;'},
            {label: 'Role Permissions', url: '#;'},
            {label: 'Activity Logs', url: '#;'},
            {label: 'Security Settings', url: '#;'},
            {label: 'User Groups', url: '#;'},
            {label: 'Authentication & Login', url: '#;'}
        ]
    }
];

const MegaMenu = () => {
    return (
        <div className="topbar-item d-none d-md-flex">
            <Dropdown>
                <DropdownToggle as={'button'}
                                className="topbar-link btn fw-medium btn-link dropdown-toggle drop-arrow-none">
                    Boom Boom! 😍<TbChevronDown className="ms-1"/>
                </DropdownToggle>
                <DropdownMenu className="dropdown-menu-xxl p-0">
                    <SimpleBar className="h-100" style={{maxHeight: '380px'}}>
                        <Row className="g-0">
                            <Col className="col-12">
                                <div className="p-3 text-center bg-light bg-opacity-50">
                                    <h4 className="mb-0 fs-lg fw-semibold">Welcome to <span
                                        className="text-primary">INSPINIA+</span> Admin Theme.</h4>
                                </div>
                            </Col>
                        </Row>
                        <Row className="g-0">
                            {
                                megaMenuItems.map((item, idx) => (
                                    <Col md={4} key={idx}>
                                        <div className="p-3">
                                            <h5 className="mb-2 fw-semibold fs-sm dropdown-header">{item.title}</h5>
                                            <ul className="list-unstyled megamenu-list">

                                                {
                                                    item.links.map((link, index) => (
                                                        <li key={index}>
                                                            <Link to={link.url}
                                                                  className="dropdown-item">{link.label}</Link>
                                                        </li>
                                                    ))
                                                }
                                            </ul>
                                        </div>
                                    </Col>
                                ))
                            }
                        </Row>
                    </SimpleBar>
                </DropdownMenu>
            </Dropdown>

        </div>
    )
}

export default MegaMenu;
