// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/layouts/compact/compact.component.ts
import {Component} from '@angular/core';
import {NgIcon} from '@ng-icons/core';
import {NgbAlert} from '@ng-bootstrap/ng-bootstrap';
import {PageTitleComponent} from '@app/components/page-title.component';

@Component({
    selector: 'app-compact',
    imports: [
        NgIcon,
        NgbAlert,
        PageTitleComponent
    ],
    templateUrl: './compact.component.html'
})
export class CompactComponent {

}

<div class="container-fluid">
    <app-page-title title="Compact"/>
</div>

<div class="container-xl">
    <div class="row">
        <div class="col-12">
            <ngb-alert type="info" class="alert-bordered border-start border-info d-flex align-items-start gap-2">
                <ng-icon name="tablerInfoCircle" class="fs-xxl"/>
                <div>
                    To use the compact layout, follow this structure: wrap your page title in
                    <code>&lt;div class="container-fluid"&gt;</code> and place your main content inside
                    <code>&lt;div class="container-xl"&gt;</code>. This ensures proper spacing and alignment.
                </div>
            </ngb-alert>
        </div>
    </div>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/views/layouts/sidebars/compact/index.tsx

import {useEffect} from "react";
import {Alert, Col, Container, Row} from "react-bootstrap";
import PageBreadcrumb from "@/components/PageBreadcrumb";
import {useLayoutContext} from "@/context/useLayoutContext";
import {TbInfoCircle} from "react-icons/tb";

const Page = () => {

    const {changeSideNavSize, reset} = useLayoutContext()


    useEffect(() => {
        changeSideNavSize('compact')

        return () => reset()
    }, [])

    return (
        <Container fluid>
            <PageBreadcrumb title="Compact Menu"/>

            <Row>
                <Col sm={12}>
                    <Alert variant="info"
                           className="alert-bordered border-start border-info d-flex align-items-start gap-2">
                        <TbInfoCircle className="fs-xxl"/>
                        <div>
                            To switch to a medium-sized (compact) sidebar,
                            add <code>data-sidenav-size="compact"</code> to
                            the <code>&lt;html&gt;</code> tag. To apply this dynamically,
                            use <code>changeSideNavSize('compact')</code> from the <code>LayoutContext</code>.
                        </div>
                    </Alert>
                </Col>
            </Row>
        </Container>
    )
}

export default Page
