// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/sidenav/components/app-menu/app-menu.component.ts
import {Component, inject, OnInit, TemplateRef, ViewChild} from '@angular/core';
import {MenuItemType} from '@/app/types/layout';
import {CommonModule} from '@angular/common';
import {NgIcon} from '@ng-icons/core';
import {NgbCollapse} from '@ng-bootstrap/ng-bootstrap';
import {NavigationEnd, Router, RouterLink} from '@angular/router';
import {filter} from 'rxjs';
import {scrollToElement} from '@/app/utils/layout-utils';
import {menuItems} from '@layouts/components/data';
import {LayoutStoreService} from '@core/services/layout-store.service';

@Component({
    selector: 'app-menu',
    imports: [CommonModule, NgIcon, NgbCollapse, RouterLink],
    templateUrl: './app-menu.component.html'
})
export class AppMenuComponent implements OnInit {

    router = inject(Router)
    layout = inject(LayoutStoreService)

    @ViewChild('MenuItemWithChildren', {static: true})
    menuItemWithChildren!: TemplateRef<{ item: MenuItemType }>;

    @ViewChild('MenuItem', {static: true})
    menuItem!: TemplateRef<{ item: MenuItemType }>;

    menuItems = menuItems;

    ngOnInit(): void {
        this.router.events
            .pipe(filter(event => event instanceof NavigationEnd))
            .subscribe(() => {
                this.expandActivePaths(this.menuItems);
                setTimeout(() => this.scrollToActiveLink(), 50);
            });

        this.expandActivePaths(this.menuItems);
        setTimeout(() => this.scrollToActiveLink(), 100);
    }

    hasSubMenu(item: MenuItemType): boolean {
        return !!item.children;
    }

    expandActivePaths(items: MenuItemType[]) {
        for (const item of items) {
            if (this.hasSubMenu(item)) {
                item.isCollapsed = !this.isChildActive(item);
                this.expandActivePaths(item.children || []);
            }
        }
    }

    isChildActive(item: MenuItemType): boolean {
        if (item.url && this.router.url === item.url) return true;
        if (!item.children) return false;
        return item.children.some((child: MenuItemType) => this.isChildActive(child));
    }

    isActive(item: MenuItemType): boolean {
        return this.router.url === item.url;
    }

    scrollToActiveLink(): void {
        const activeItem = document.querySelector('[data-active-link="true"]') as HTMLElement;
        const scrollContainer = document.querySelector("#sidenav .simplebar-content-wrapper") as HTMLElement;

        if (activeItem && scrollContainer) {
            const containerRect = scrollContainer.getBoundingClientRect();
            const itemRect = activeItem.getBoundingClientRect();

            const offset = itemRect.top - containerRect.top - window.innerHeight * 0.4;

            scrollToElement(scrollContainer, scrollContainer.scrollTop + offset, 500);
        }
    }

    hideBackDrop(url: string): void {
        if (this.layout.sidenavSize === 'offcanvas' && this.router.url !== url) {
            this.layout.hideBackdrop();
        }
    }
}

<ul class="side-nav">
    <ng-container *ngFor="let item of menuItems">

        <li *ngIf="item.isTitle" class="side-nav-title">{{ item.label }}</li>

        <ng-container *ngIf="!item.isTitle">
            <!-- menu item without any child -->
            <ng-container *ngIf="!hasSubMenu(item)">
                <ng-container *ngTemplateOutlet="MenuItem;context:{item}"/>
            </ng-container>

            <!-- menu item with child -->
            <ng-container *ngIf="hasSubMenu(item)">
                <ng-container *ngTemplateOutlet="MenuItemWithChildren;context:{item}"/>
            </ng-container>
        </ng-container>

    </ng-container>
</ul>

<ng-template #MenuItemWithChildren let-item="item">
    <li class="side-nav-item" [ngClass]="{'active': isChildActive(item)}">
        <button (click)="item.isCollapsed = !item.isCollapsed" class="side-nav-link"
                [attr.aria-expanded]="!item.isCollapsed">
      <span *ngIf="item.icon" class="menu-icon">
        <ng-icon [name]="item.icon"></ng-icon>
      </span>
            <span class="menu-text">{{ item.label }}</span>
            <span *ngIf="item.badge" [class]="`badge bg-${item.badge.variant}`">{{ item.badge.text }}</span>
            <span *ngIf="!item.badge" class="menu-arrow">
                <ng-icon name="tablerChevronDown"></ng-icon>
            </span>
        </button>
        <div #collapse="ngbCollapse" [(ngbCollapse)]="item.isCollapsed" class="collapse">
            <ul class="sub-menu">
                <ng-container *ngFor="let child of item.children">
                    <!-- menu item without any child -->
                    <ng-container *ngIf="!hasSubMenu(child)">
                        <ng-container *ngTemplateOutlet="MenuItem;context:{item:child}"/>
                    </ng-container>

                    <!-- menu item with child -->
                    <ng-container *ngIf="hasSubMenu(child)">
                        <ng-container *ngTemplateOutlet="MenuItemWithChildren;context:{item:child}"/>
                    </ng-container>
                </ng-container>
            </ul>
        </div>
    </li>
</ng-template>

<ng-template #MenuItem let-item="item">
    <li class="side-nav-item" [ngClass]="{'active': isActive(item)}">
        <a *ngIf="item.url" [routerLink]="item.url" [target]="item.target" class="side-nav-link"
           [ngClass]="{'disabled': item.isDisabled,'special-menu': item.isSpecial, 'active': isActive(item)}"
           [attr.data-active-link]="isActive(item)"
           (click)="hideBackDrop(item.url)"
        >
      <span *ngIf="item.icon" class="menu-icon">
        <ng-icon [name]="item.icon"></ng-icon>
      </span>
            <span class="menu-text">{{ item.label }}</span>
            <span *ngIf="item.badge" [ngClass]="`badge text-bg-${item.badge.variant} opacity-50`"
                  [innerHTML]="item.badge.text"></span>
        </a>
    </li>
</ng-template>

// src_old/layouts/components/sidenav/components/AppMenu.tsx
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Collapse } from "react-bootstrap";
import { TbChevronDown } from "react-icons/tb";
import { useLayoutContext } from "@/context/useLayoutContext";
import { getUserInfo } from "@/utils/auth";
import { scrollToElement } from "@/helpers/layout";
import { menuItems } from "@/layouts/components/data";
import type { MenuItemType } from "@/types/layout";

const MenuItemWithChildren = ({
  item,
  openMenuKey,
  setOpenMenuKey,
  level = 0,
}: {
  item: MenuItemType;
  openMenuKey: string | null;
  setOpenMenuKey: (key: string | null) => void;
  level?: number;
}) => {
  const { pathname } = useLocation();
  const isTopLevel = level === 0;

  const [localOpen, setLocalOpen] = useState(false);
  const [didAutoOpen, setDidAutoOpen] = useState(false);

  const isChildActive = (children: MenuItemType[]): boolean =>
    children.some(
      (child) =>
        (child.url && pathname.startsWith(child.url)) ||
        (child.children && isChildActive(child.children))
    );

  const isActive = isChildActive(item.children || []);
  const isOpen = isTopLevel ? openMenuKey === item.key : localOpen;

  useEffect(() => {
    if (isActive && !didAutoOpen) {
      isTopLevel ? setOpenMenuKey(item.key) : setLocalOpen(true);
      setDidAutoOpen(true);
    }
  }, [isActive, isTopLevel, item.key, setOpenMenuKey, didAutoOpen]);

  const toggleOpen = () => {
    isTopLevel ? setOpenMenuKey(isOpen ? null : item.key) : setLocalOpen(!localOpen);
  };

  return (
    <li className={`side-nav-item ${isOpen ? "active" : ""}`}>
      <button className="side-nav-link" onClick={toggleOpen} aria-expanded={isOpen}>
        {item.icon && <span className="menu-icon"><item.icon /></span>}
        <span className="menu-text">{item.label}</span>
        <span className="menu-arrow"><TbChevronDown /></span>
      </button>
      <Collapse in={isOpen}>
        <div>
          <ul className="sub-menu">
            {(item.children || []).map((child) =>
              child.children ? (
                <MenuItemWithChildren
                  key={child.key}
                  item={child}
                  openMenuKey={openMenuKey}
                  setOpenMenuKey={setOpenMenuKey}
                  level={level + 1}
                />
              ) : (
                <MenuItem key={child.key} item={child} />
              )
            )}
          </ul>
        </div>
      </Collapse>
    </li>
  );
};

const MenuItem = ({ item }: { item: MenuItemType }) => {
  const { pathname } = useLocation();
  const { sidenav, hideBackdrop } = useLayoutContext();
  const isActive = item.url && pathname.startsWith(item.url);

  const handleClick = () => {
    if (sidenav.size === "offcanvas") hideBackdrop();
  };

  return (
    <li className={`side-nav-item ${isActive ? "active" : ""}`}>
      <Link
        to={item.url ?? "/"}
        className={`side-nav-link ${isActive ? "active" : ""} ${item.isDisabled ? "disabled" : ""}`}
        onClick={handleClick}
      >
        {item.icon && <span className="menu-icon"><item.icon /></span>}
        <span className="menu-text">{item.label}</span>
        {item.badge && (
          <span className={`badge bg-${item.badge.variant}`}>{item.badge.text}</span>
        )}
      </Link>
    </li>
  );
};

const AppMenu = () => {
  const [openMenuKey, setOpenMenuKey] = useState<string | null>(null);
  const user = getUserInfo();
  // const userLevel: number = user?.type ?? 0;
  const userLevel = parseInt(user?.type ?? "0", 10);

  const filterMenuItems = (items: MenuItemType[]): MenuItemType[] =>
    items
      .filter(item => {
        const allowedLevels = item.minLevel ?? [];
        return allowedLevels.length === 0 || allowedLevels.includes(userLevel);
      })
      .map(item => ({
        ...item,
        children: item.children ? filterMenuItems(item.children) : undefined,
      }));

  const visibleMenuItems = useMemo(() => filterMenuItems(menuItems), [userLevel]);

  useEffect(() => {
    const activeItem: HTMLElement | null = document.querySelector(".side-nav-link.active");
    if (activeItem) {
      const wrapper = document.querySelector("#sidenav .simplebar-content-wrapper");
      if (wrapper) {
        const offset = activeItem.offsetTop - window.innerHeight * 0.4;
        scrollToElement(wrapper, offset, 500);
      }
    }
  }, []);

  useEffect(() => {
    // console.log("User Level:", userLevel);
    // console.log("Visible Menu Items:", visibleMenuItems);
  }, [userLevel, visibleMenuItems]);

  return (
    <ul className="side-nav">
      {visibleMenuItems.map((item) =>
        item.isTitle ? (
          <li className="side-nav-title" key={item.key}>{item.label}</li>
        ) : item.children ? (
          <MenuItemWithChildren
            key={item.key}
            item={item}
            openMenuKey={openMenuKey}
            setOpenMenuKey={setOpenMenuKey}
          />
        ) : (
          <MenuItem key={item.key} item={item} />
        )
      )}
    </ul>
  );
};

export default AppMenu;
