// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/sidenav/components/user-profile/user-profile.component.ts
import {Component, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
import {RouterLink} from '@angular/router';
import {NgbCollapseModule, NgbDropdown, NgbDropdownMenu, NgbDropdownToggle} from '@ng-bootstrap/ng-bootstrap';
import {CommonModule} from '@angular/common';
import {NgIcon} from '@ng-icons/core';
import {userDropdownItems} from '@layouts/components/data';

@Component({
  selector: 'app-user-profile',
  imports: [
    RouterLink,
    NgbCollapseModule,
    NgbDropdown,
    NgbDropdownToggle,
    NgbDropdownMenu,
    CommonModule,
    NgIcon
  ],

  templateUrl: './user-profile.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class UserProfileComponent {
  menuItems = userDropdownItems
}

<div class="sidenav-user">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <a routerLink="pages-profile.html" class="link-reset">
        <img src="assets/images/users/user-2.jpg" alt="user-image"
             class="rounded-circle mb-2 avatar-md">
        <span class="sidenav-user-name fw-bold">Damian D.</span>
        <span class="fs-12 fw-semibold" data-lang="user-role">Art Director</span>
      </a>
    </div>
    <div ngbDropdown [placement]="'bottom-end'">
      <button ngbDropdownToggle
              class="btn btn-link p-0 dropdown-toggle drop-arrow-none link-reset sidenav-user-set-icon">
        <ng-icon name="tablerSettings" size="24" class="align-middle ms-1" />
      </button>

      <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end mt-1">

        <div *ngFor="let item of menuItems">
          <div *ngIf="item.isHeader" class="dropdown-header noti-title">
            <h6 class="text-overflow m-0">{{ item.label }}</h6>
          </div>

          <div *ngIf="item.isDivider" class="dropdown-divider"></div>

          <a *ngIf="!item.isHeader && !item.isDivider" [routerLink]="item.url" class="dropdown-item" [ngClass]="item.class">
            <ng-icon [name]="item.icon" size="17" class="align-middle d-inline-flex align-items-center me-2"/>
            <span class="align-middle" [innerHTML]="item.label"></span>
          </a>
        </div>

      </div>
    </div>
  </div>
</div>

// src_old/layouts/components/sidenav/components/UserProfile.tsx
import { Link } from "react-router";
import {Fragment} from "react";
import {TbSettings} from "react-icons/tb";
import {Dropdown, DropdownDivider, DropdownItem, DropdownMenu, DropdownToggle} from "react-bootstrap";
import {userDropdownItems} from "@/layouts/components/data";

import user2 from "@/assets/images/users/user-2.jpg"
import { getUserInfo } from '@/utils/auth';
import { capitalizeWords } from '@/utils/stringUtils'; // adjust path if needed


const UserProfile = () => {
    const UserInfo = getUserInfo();
    return (
        <div className="sidenav-user">
            <div className="d-flex justify-content-between align-items-center">
                <div>
                    <Link to="/dashboard" className="link-reset">
                        <img src={user2} alt="user-image" width="36" height="36"
                               className="rounded-circle mb-2 avatar-md"/>
                        <span className="sidenav-user-name fw-bold">{UserInfo?.full_name ? capitalizeWords(UserInfo.full_name) : ''}</span>
                        <span className="fs-12 fw-semibold d-block" data-lang="user-role">{UserInfo?.role ? capitalizeWords(UserInfo.role) : ''}</span>
                        <span className="fs-12 fw-semibold" data-lang="user-role">{UserInfo?.region_name ? capitalizeWords(UserInfo.region_name) : ''}</span>
                    </Link>
                </div>
                <Dropdown>
                    <DropdownToggle as={'a'} role="button" aria-label="profile dropdown"
                                    className="dropdown-toggle drop-arrow-none link-reset sidenav-user-set-icon">
                        <TbSettings className="fs-24 align-middle ms-1"/>
                    </DropdownToggle>

                    <DropdownMenu>
                        {
                            userDropdownItems.map((item, idx) => (
                                <Fragment key={idx}>
                                    {
                                        item.isHeader ?
                                            <div className="dropdown-header noti-title">
                                                <h6 className="text-overflow m-0">{item.label}</h6>
                                            </div> :
                                            item.isDivider ? <DropdownDivider/> :
                                                <DropdownItem as={Link} to={item.url ?? '#'} className={item.class}>
                                                    {
                                                        item.icon &&
                                                        <item.icon className="me-2 fs-17 align-middle"/>
                                                    }
                                                    <span className="align-middle">{item.label}</span>
                                                </DropdownItem>
                                    }
                                </Fragment>
                            ))
                        }
                    </DropdownMenu>
                </Dropdown>
            </div>
        </div>
    )
}

export default UserProfile
