// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/landing/components/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component, HostListener, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import {LayoutStoreService} from '@core/services/layout-store.service';
import { ScrollService } from '@core/services/scroll.service';
import { NgbAlert, NgbCollapseModule } from '@ng-bootstrap/ng-bootstrap';
import { NgIcon } from '@ng-icons/core';

@Component({
    selector: 'app-header',
    imports: [NgIcon, RouterLink, CommonModule, NgbCollapseModule, NgbAlert],
    templateUrl: './header.component.html',
    styles: ``
})
export class HeaderComponent {
    isCollapsed = true;
    isSticky = false;
    isOpen = true
    public scroll = inject(ScrollService)
    public layout = inject(LayoutStoreService)

    navItems = ['Home', 'Services', 'Features', 'Plans', 'Reviews', 'Blog', 'Contact'];

    @HostListener('window:scroll', [])
    onWindowScroll() {
        const scroll = window.scrollY || window.pageYOffset;
        this.isSticky = scroll > 100;
    }

    closeAlert() {
        this.isOpen = false
    }

    toggleTheme() {
        if (this.layout.theme === 'light') {
            this.layout.setTheme('dark')
        } else {
            this.layout.setTheme('light')
        }
    }
}

<ngb-alert  *ngIf="isOpen" [dismissible]="false" type="primary" class="top-alert text-center mb-0 rounded-0" role="alert">
    <button type="button" class="btn-close btn-close-white float-end" aria-label="Close" (click)="closeAlert()"></button>
    <div class="fst-italic fw-medium">🚀 INSPINIA 4.x is here! Now with Bootstrap 5, dark mode, and a refreshed UI.
        Upgrade today for the best experience! <a
        href="https://wrapbootstrap.com/theme/inspinia-multipurpose-admin-dashboard-template-WB0R5L90S?ref=inspinia"
        target="_blank" class="fw-semibold fst-normal text-white text-decoration-underline link-offset-3 ms-2">Buy
        Now!</a></div>
</ngb-alert>
<header>

    <nav class="navbar navbar-expand-lg py-3 sticky-top {{isSticky ? 'top-scroll-up top-fixed': ''}}" id="landing-navbar">
        <div class="container">
            <div class="auth-brand mb-0">
                <a routerLink="/" class="logo-dark">
                    <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                </a>
                <a routerLink="/" class="logo-light">
                    <img src="assets/images/logo.png" alt="logo" height="32">
                </a>
            </div>

            <button class="navbar-toggler" type="button" (click)="isCollapsed = !isCollapsed"
                [attr.aria-expanded]="!isCollapsed" aria-controls="navbarSupportedContent"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div [ngbCollapse]="isCollapsed" class="navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav fw-medium gap-2 fs-sm mx-auto mt-2 mt-lg-0" id="navbar-example">
                    <li class="nav-item" *ngFor="let item of navItems">
                        <a class="nav-link" [class.active]="scroll.activeSection === (item.toLowerCase())"
                            (click)="scroll.scrollTo(item)" href="javascript:void(0)">{{ item
                            }}</a>
                    </li>
                </ul>

                <div>
                    <button class="btn btn-link btn-icon fw-semibold text-body" type="button" (click)="toggleTheme()">
                        <ng-icon name="tablerContrast" class="ti ti-contrast fs-22"></ng-icon>
                    </button>
                    <a routerLink="/auth-sign-in" class="btn btn-link fw-semibold text-body ps-2">SIGN IN</a>
                    <a routerLink="/auth-sign-up" class="btn btn-sm btn-primary">Sign Up</a>
                </div>
            </div>
        </div>
    </nav>


</header>

// src/views/landing/components/Header.tsx
;
import AppLogo from '@/components/AppLogo';
import { useLayoutContext } from '@/context/useLayoutContext';
import useScrollEvent from '@/hooks/useScrollEvent';
import { Link } from "react-router";;
import { useState } from 'react';
import { Alert, Button, Container, Nav, Navbar, NavbarBrand, NavbarCollapse, NavbarToggle, NavLink } from 'react-bootstrap';
import { TbContrast } from 'react-icons/tb';

const navItems = ['Home', 'Services', 'Features', 'Plans', 'Reviews', 'Blog', 'Contact'];

export default function Header() {
    const { theme, changeTheme } = useLayoutContext()

    const toggleTheme = () => {
        if (theme === "dark") {
            changeTheme('light')
            return;
        }
        changeTheme('dark');
        return;
    }
    const [isCollapsed, setIsCollapsed] = useState(true);
    const { scrollY } = useScrollEvent()

    return (
        <>
            <Alert variant="primary" className="top-alert text-center mb-0 rounded-0" dismissible closeVariant="white">
                <div className="fst-italic fw-medium">
                    🚀 INSPINIA 4.x is here! Now with Bootstrap 5, dark mode, and a refreshed UI.
                    Upgrade today for the best experience!
                    <a
                        href="https://wrapbootstrap.com/theme/inspinia-multipurpose-admin-dashboard-template-WB0R5L90S?ref=inspinia"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="fw-semibold fst-normal text-white text-decoration-underline link-offset-3 ms-2"
                    >
                        Buy Now!
                    </a>
                </div>
            </Alert>

            <header>
                <Navbar
                    expand="lg"
                    className={`py-3 sticky-top ${scrollY > 100 && 'top-scroll-up top-fixed'}`}
                    id="landing-navbar"
                >
                    <Container>
                        <NavbarBrand className="auth-brand mb-0">
                            <AppLogo />
                        </NavbarBrand>

                        <NavbarToggle
                            aria-controls="navbarSupportedContent"
                            onClick={() => setIsCollapsed(!isCollapsed)}
                        />
                        <NavbarCollapse in={!isCollapsed} id="navbarSupportedContent">
                            <Nav className="fw-medium gap-2 fs-sm mx-auto mt-2 mt-lg-0">
                                {navItems.map((item, idx) => (
                                    <li className="nav-item" key={idx}>
                                        <NavLink
                                            className="nav-link"
                                            href={`#${item.toLowerCase()}`}
                                        >
                                            {item}
                                        </NavLink>
                                    </li>
                                ))}
                            </Nav>
                            <div className="d-flex align-items-center">
                                <Button variant="link" className="btn-icon fw-semibold text-body me-2" onClick={toggleTheme}>
                                    <TbContrast className="fs-22" />
                                </Button>
                                <Link to="/auth-sign-in" className="btn btn-link fw-semibold text-body ps-2">SIGN IN</Link>
                                <Link to="/auth-sign-up" className="btn btn-sm btn-primary ms-2">Sign Up</Link>
                            </div>
                        </NavbarCollapse>
                    </Container>
                </Navbar>
            </header>
        </>
    );
}
