// src_old/views/layouts/scrollable/index.tsx

import {useEffect} from "react";
import {Alert, Col, Container, Row} from "react-bootstrap";
import PageBreadcrumb from "@/components/PageBreadcrumb";
import {useLayoutContext} from "@/context/useLayoutContext";
import {TbInfoCircle} from "react-icons/tb";

const Page = () => {

    const {changeLayoutPosition, reset} = useLayoutContext()

    useEffect(() => {
        changeLayoutPosition('scrollable')

        return () => reset()
    }, [])

    return (
        <Container fluid>
            <PageBreadcrumb title="Scrollable"/>

            <Row>
                <Col sm={12}>
                    <Alert variant="info"
                           className="alert-bordered border-start border-info d-flex align-items-start gap-2">
                        <TbInfoCircle className="fs-xxl"/>
                        <div>
                            To enable full scrolling and view all content, please
                            add <code>data-layout-position="scrollable"</code> to the
                            <code>&lt;html&gt;</code> tag. To apply this dynamically,
                            use <code>changeLayoutPosition('scrollable')</code> from the <code>LayoutContext</code>.
                        </div>
                    </Alert>
                </Col>
            </Row>

            {/*demo only*/}
            <div style={{height: '1000px'}}></div>
        </Container>
    )
}

export default Page

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/layouts/scrollable/scrollable.component.ts
import {Component, inject, OnDestroy, OnInit} from '@angular/core';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {PageTitleComponent} from '@app/components/page-title.component';
import {NgIcon} from '@ng-icons/core';
import {NgbAlert} from '@ng-bootstrap/ng-bootstrap';

@Component({
    selector: 'app-scrollable',
    imports: [
        PageTitleComponent,
        NgIcon,
        NgbAlert
    ],
    templateUrl: './scrollable.component.html'
})
export class ScrollableComponent implements OnInit, OnDestroy {

    layout = inject(LayoutStoreService)

    ngOnInit() {
        this.layout.setLayoutPosition('scrollable')
    }

    ngOnDestroy() {
        this.layout.reset()
    }
}

<div class="container-fluid">
    <app-page-title title="Scrollable"/>

    <div class="row">
        <div class="col-12">
            <ngb-alert type="info" class="alert-bordered border-start border-info d-flex align-items-start gap-2">
                <ng-icon name="tablerInfoCircle" class="fs-xxl"/>
                <div>
                    To enable full scrolling and view all content, add
                    <code>data-layout-position="scrollable"</code> to the
                    <code>&lt;html&gt;</code> tag. You can apply this dynamically using the
                    <code>LayoutStoreService</code>
                    with
                    <code>setLayoutPosition('scrollable')</code>.
                </div>
            </ngb-alert>


            <!-- Demo Only -->
            <div class="card">
                <div class="card-body" style="height: 1200px"></div>
            </div>
        </div>
    </div>
</div>
