// files/INSPINIA_v4.2.0/React/Seed/src/views/landing/index.tsx

import Blogs from "./components/Blogs"
import CTA from "./components/CTA"
import Features from "./components/Features"
import Header from "./components/Header"
import Hero from "./components/Hero"
import PricingPlans from "./components/PricingPlans"
import Services from "./components/Services"
import Testimonials from "./components/Testimonials"
import Contact from "./components/Contact"
import Footer from "./components/Footer"

const Landing = () => {
    return (
        <div className="bg-body-secondary">
            <Header />
            <Hero />
            <Services />
            <Features />
            <PricingPlans />
            <CTA />
            <Testimonials />
            <Blogs />
            <Contact />
            <Footer />
        </div>
    )
}

export default Landing

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/landing/landing.component.ts
import { Component } from '@angular/core';
import { CtaComponent } from "./components/cta/cta.component";
import { FeaturesComponent } from "./components/features/features.component";
import { HeaderComponent } from "./components/header/header.component";
import { HeroComponent } from "./components/hero/hero.component";
import { PricingPlansComponent } from "./components/pricing-plans/pricing-plans.component";
import { ServicesComponent } from "./components/services/services.component";
import { TestimonialsComponent } from "./components/testimonials/testimonials.component";
import { BlogsComponent } from "./components/blogs/blogs.component";
import { ContactComponent } from "./components/contact/contact.component";
import { FooterComponent } from './components/footer/footer.component';

@Component({
  selector: 'app-landing',
  imports: [HeaderComponent, HeroComponent, ServicesComponent, FeaturesComponent, PricingPlansComponent, CtaComponent, TestimonialsComponent, BlogsComponent, ContactComponent, FooterComponent],
  templateUrl: './landing.component.html',
  styles: ``
})
export class LandingComponent {

}

<div class="bg-body-secondary">
    <app-header />
    <app-hero />
    <app-services />
    <app-features />
    <app-pricing-plans />
    <app-cta />
    <app-testimonials />
    <app-blogs />
    <app-contact />
    <app-footer />
</div>
