// src/views/auth/auth-3/lock-screen/index.tsx
import avatar from '@/assets/images/users/user-1.jpg'
import AppLogo from "@/components/AppLogo"
import { author, currentYear } from "@/helpers"


import { Link } from "react-router";
import { Button, Card, CardBody, Col, Form, FormControl, InputGroup, Row } from "react-bootstrap"

const LockScreen = () => {
    return (
        <div className="auth-box p-0 w-100">
            <Row className="w-100 g-0">
                <Col>
                    <div className="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                        <div className="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                        </div>
                    </div>
                </Col>

                <Col xl="auto">
                    <Card className="auth-box-form border-0 mb-0">
                        <CardBody className="min-vh-100 d-flex flex-column justify-content-center">
                            <div className="auth-brand mb-0 text-center">
                                <AppLogo />
                            </div>

                            <div className="mt-auto text-center">
                                <h4 className="fw-bold">Lock Screen ! | IN+</h4>
                                <p className="text-muted mx-auto mb-5">Let&apos;s get you signed in. Enter your PIN to continue</p>

                                <div className="text-center mb-4">
                                    <img
                                        src={avatar}
                                        className="rounded-circle img-thumbnail avatar-xxl mb-2"
                                        alt="thumbnail"
                                        width={120}
                                        height={120}
                                    />
                                    <h5 className="fs-md">Damian D.</h5>
                                </div>

                                <Form>
                                    <div className="mb-3">
                                        <InputGroup>
                                            <FormControl
                                                type="password"
                                                className="py-2 px-3 bg-light bg-opacity-40 border-light"
                                                id="userPassword"
                                                placeholder="Enter password"
                                                required
                                            />
                                        </InputGroup>
                                    </div>

                                    <div className="d-grid">
                                        <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                            Unlock
                                        </Button>
                                    </div>
                                </Form>

                                <p className="mt-4 text-muted text-center mb-4">
                                    Not you? Return to{' '}
                                    <Link to="/auth-3/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                        Sign in
                                    </Link>
                                </p>
                            </div>

                            <p className="text-center text-muted mt-auto mb-0">
                                © 2014 -{' '}
                                <span >{currentYear}</span> INSPINIA — by{' '}
                                <span className="fw-semibold">{author}</span>
                            </p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </div>
    )
}

export default LockScreen

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version3/lock-screen/lock-screen.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-lock-screen',
    host: { 'data-component-id': 'auth3-lock-screen' },
    imports: [RouterLink],
    templateUrl: './lock-screen.component.html',
    styles: ``,
    schemas:[CUSTOM_ELEMENTS_SCHEMA]
})
export class LockScreenComponent {
    currentYear = currentYear
    credits = credits
}

    <div class="auth-box p-0 w-100">
        <div class="row w-100 g-0">
            <div class="col">
                <div class="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                    <div class="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                    </div>
                </div>
            </div>

            <div class="col-xl-auto">
                <div class="card auth-box-form border-0 mb-0">
                    <div class="card-body min-vh-100 d-flex flex-column justify-content-center">
                        <div class="auth-brand mb-0 text-center">
                            <a routerLink="/" class="logo-dark">
                                <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                            </a>
                            <a routerLink="/" class="logo-light">
                                <img src="assets/images/logo.png" alt="logo" height="32">
                            </a>
                        </div>

                        <div class="mt-auto text-center">
                            <h4 class="fw-bold">Lock Screen ! | IN+</h4>
                            <p class="text-muted mx-auto mb-5">Let’s get you signed in. Enter your PIN to continue</p>



                            <div class="text-center mb-4">
                                <img src="assets/images/users/user-1.jpg" class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                                <h5 class="fs-md">Damian D.</h5>
                            </div>

                            <form>

                                <div class="mb-3">
                                    <div class="input-group">
                                        <input type="password" class="form-control py-2 px-3 bg-light bg-opacity-40 border-light" id="userPassword" placeholder="Enter password" required>
                                    </div>
                                </div>

                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary fw-semibold py-2">Unlock</button>
                                </div>
                            </form>

                            <p class="mt-4 text-muted text-center mb-4">
                                Not you? Return to <a routerLink="/auth-3/sign-in" class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                            </p>
                        </div>
                        
                        <p class="text-center text-muted mt-auto mb-0">
                            © 2014 -
                           {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
