// rawfiles/src/views/auth/auth-3/sign-up/index.tsx

import AppLogo from '@/components/AppLogo'
import PasswordInputWithStrength from '@/components/PasswordInputWithStrength'
import { author, currentYear } from '@/helpers'
import { Link } from "react-router";
import { useState } from 'react'
import { Button, Card, CardBody, Col, Form, InputGroup, Row } from 'react-bootstrap'


const SignUp = () => {
    const [password, setPassword] = useState('');
    return (
        <div className="auth-box p-0 w-100">
            <Row className="w-100 g-0">
                <Col>
                    <div className="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                        <div className="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center"></div>
                    </div>
                </Col>

                <Col md="auto">
                    <Card className="auth-box-form border-0 mb-0">
                        <CardBody className="min-vh-100 d-flex flex-column justify-content-center">
                            <div className="auth-brand mb-0 text-center">
                                <AppLogo />
                            </div>

                            <div className="mt-auto text-center">
                                <h4 className="fw-bold">Register to IN+</h4>
                                <p className="text-muted auth-sub-text mx-auto">
                                    Let’s get you Sign Up. Enter your email and password to continue.
                                </p>

                                <Form className="mt-4">
                                    <div className="mb-3">
                                        <InputGroup>
                                            <input
                                                type="text"
                                                className="form-control py-2 px-3 bg-light bg-opacity-40 border-light"
                                                id="userName"
                                                placeholder="Enter name"
                                                required
                                            />
                                        </InputGroup>
                                    </div>

                                    <div className="mb-3">
                                        <InputGroup>
                                            <input
                                                type="email"
                                                className="form-control py-2 px-3 bg-light bg-opacity-40 border-light"
                                                id="userEmail"
                                                placeholder="Enter email"
                                                required
                                            />
                                        </InputGroup>
                                    </div>

                                    <div className="mb-3" data-password="bar">
                                        <PasswordInputWithStrength
                                            id='userPassword'
                                            name='user-password'
                                            password={password}
                                            setPassword={setPassword}
                                            placeholder='Enter password'
                                            inputClassName='py-2 px-3 bg-light bg-opacity-40 border-light'
                                        />
                                    </div>

                                    <div className="d-flex justify-content-between align-items-center mb-3">
                                        <div className="form-check">
                                            <input
                                                className="form-check-input form-check-input-light fs-14"
                                                type="checkbox"
                                                id="termAndPolicy"
                                            />
                                            <label className="form-check-label" htmlFor="termAndPolicy">
                                                Agree the Terms & Policy
                                            </label>
                                        </div>
                                    </div>

                                    <div className="d-grid">
                                        <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                            Create Account
                                        </Button>
                                    </div>
                                </Form>
                            </div>

                            <p className="text-muted text-center mt-4 mb-0">
                                Already have an account?{' '}
                                <Link to="/auth-3/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                    Login
                                </Link>
                            </p>

                            <p className="text-center text-muted mt-auto mb-0">
                                © 2014 - <span>{currentYear}</span> INSPINIA — by{' '}
                                <span className="fw-semibold">{author}</span>
                            </p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </div>
    )
}

export default SignUp

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version3/sign-up/sign-up.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';
import { PasswordStrengthBarComponent } from "@app/components/password-strength-bar.component";
import { FormsModule } from '@angular/forms';

@Component({
    selector: 'app-sign-up',
    host: { 'data-component-id': 'auth3-sign-up' },
    imports: [RouterLink, PasswordStrengthBarComponent,FormsModule],
    templateUrl: './sign-up.component.html',
    styles: ``,
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class SignUpComponent {
    currentYear = currentYear
    credits = credits
    password: string = '';
}

<div class="auth-box p-0 w-100">
    <div class="row w-100 g-0">
        <div class="col">
            <div class="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                <div class="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">

                </div>
            </div>
        </div>

        <div class="col-md-auto">
            <div class="card auth-box-form border-0 mb-0">
                <div class="card-body min-vh-100 d-flex flex-column justify-content-center">
                    <div class="auth-brand mb-0 text-center">
                        <a routerLink="/" class="logo-dark">
                            <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a routerLink="/" class="logo-light">
                            <img src="assets/images/logo.png" alt="logo" height="32">
                        </a>
                    </div>

                    <div class="mt-auto text-center">
                        <h4 class="fw-bold">Register to IN+</h4>
                        <p class="text-muted auth-sub-text mx-auto">Let’s get you Sign Up. Enter your email and password
                            to continue.</p>

                        <form class="mt-4">
                            <div class="mb-3">
                                <div class="input-group">
                                    <input type="text"
                                        class="form-control py-2 px-3 bg-light bg-opacity-40 border-light" id="userName"
                                        placeholder="Enter name" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="input-group">
                                    <input type="email"
                                        class="form-control py-2 px-3 bg-light bg-opacity-40 border-light"
                                        id="userEmail" placeholder="Enter email" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <div class="input-group">
                                    <input type="password"
                                        class="form-control py-2 px-3 bg-light bg-opacity-40 border-light"
                                        id="userPassword" placeholder="Enter password" required name="password" [(ngModel)]="password">
                                </div>
                                <app-password-strength-bar [password]="password" />
                            </div>

                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <div class="form-check">
                                    <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                        id="termAndPolicy">
                                    <label class="form-check-label" for="termAndPolicy">Agree the Terms & Policy</label>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Create Account</button>
                            </div>
                        </form>
                    </div>

                    <p class="text-muted text-center mt-4 mb-0">
                        Already have an account? <a routerLink="/auth-3/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Login</a>
                    </p>

                    <p class="text-center text-muted mt-auto mb-0">
                        © 2014 -
                        {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
