// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/dashboards/dashboard-2/components/recent-orders/recent-orders.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterLink} from '@angular/router';
import {currency} from '@/app/constants';
import {NgIcon} from '@ng-icons/core';
import {NgbDropdown, NgbDropdownItem, NgbDropdownMenu, NgbDropdownToggle} from '@ng-bootstrap/ng-bootstrap';
import {toTitleCase} from '@/app/utils/string-utils';
import {orders} from '@/app/pages/dashboards/dashboard-2/data';

@Component({
    selector: 'app-recent-orders',
    imports: [CommonModule, RouterLink, NgIcon, NgbDropdown, NgbDropdownItem, NgbDropdownMenu, NgbDropdownToggle],
    templateUrl: './recent-orders.component.html'
})
export class RecentOrdersComponent {
    orders = orders
    currency = currency;
    toTitleCase = toTitleCase;
}

<div class="card">
    <div class="card-header justify-content-between align-items-center border-dashed">
        <h4 class="card-title mb-0">Recent Orders</h4>
        <div class="d-flex gap-2">
            <a routerLink="" class="btn btn-sm btn-soft-secondary">
                <ng-icon name="tablerPlus" class="me-1"/>
                Add Order
            </a>
            <a routerLink="" class="btn btn-sm btn-primary">
                <ng-icon name="tablerFileExport" class="me-1"/>
                Export CSV
            </a>
        </div>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-centered table-custom table-sm table-nowrap table-hover mb-0">
                <tbody>
                <tr *ngFor="let order of orders">
                    <td>
                        <div class="d-flex align-items-center">
                            <img [src]="order.user.image" alt=""
                                 class="avatar-sm rounded-circle me-2">
                            <div>
                                <h5 class="fs-base my-1"><a [routerLink]="order.url"
                                                            class="text-body">#{{ order.id }}</a></h5>
                                <span class="text-muted fs-xs">{{ order.user.name }}</span>
                            </div>
                        </div>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Product</span>
                        <h5 class="fs-base mt-1 fw-normal">{{ order.product }}</h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Date</span>
                        <h5 class="fs-base mt-1 fw-normal">{{ order.date }}</h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Amount</span>
                        <h5 class="fs-base mt-1 fw-normal">{{ currency }}{{ order.amount }}</h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Status</span>
                        <h5 class="fs-base mt-1 fw-normal">
                            <ng-icon name="tablerCircleFill"
                                     [class]="`fs-xs text-${order.variant}`"/>
                            {{ toTitleCase(order.status) }}
                        </h5>
                    </td>
                    <td style="width: 30px;">
                        <div ngbDropdown class="dropdown">
                            <button ngbDropdownToggle
                                    class="dropdown-toggle text-muted drop-arrow-none card-drop p-0 bg-transparent border-0">
                                <ng-icon name="tablerDotsVertical" class="fs-lg"/>
                            </button>
                            <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
                                <a routerLink="" ngbDropdownItem class="dropdown-item">View Details</a>
                                <a routerLink="" ngbDropdownItem class="dropdown-item">Cancel Order</a>
                            </div>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>

    <div class="card-footer border-0">
        <div class="align-items-center justify-content-between row text-center text-sm-start">
            <div class="col-sm">
              <span class="text-muted">Showing <span
                  class="fw-semibold">1</span> to <span class="fw-semibold">5</span> of <span
                  class="fw-semibold">10</span> orders
                </span>
            </div>
            <div class="col-sm-auto mt-3 mt-sm-0">
                <ul class="pagination pagination-boxed mb-0 justify-content-center">
                    <li class="page-item disabled">
                        <a routerLink="" class="page-link">
                            <ng-icon name="tablerChevronLeft"/>
                        </a>
                    </li>
                    <li class="page-item active">
                        <a routerLink="" class="page-link">1</a>
                    </li>
                    <li class="page-item">
                        <a routerLink="" class="page-link">2</a>
                    </li>
                    <li class="page-item disabled">
                        <a routerLink="" class="page-link">
                            <ng-icon name="tablerChevronRight"/>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/views/dashboards/dashboard/components/RecentOrders.tsx
import { Link } from "react-router";
import { Button, Card, CardBody, CardFooter, CardHeader, CardTitle, Col, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, Table } from 'react-bootstrap'
import { TbCircleFilled, TbDotsVertical, TbFileExport, TbPlus } from 'react-icons/tb'

import CardPagination from '@/components/cards/CardPagination'
import { orders } from '../data'

const RecentOrders = () => {
  return (
    <Col xxl={6}>
    <Card>
      <CardHeader className="justify-content-between align-items-center border-dashed">
        <CardTitle as="h4" className="mb-0">Recent Orders</CardTitle>
        <div className="d-flex gap-2">
          <Button href="javascript:void(0);" variant="soft-secondary" size="sm">
            <TbPlus className="me-1" /> Add Order
          </Button>
          <Button href="javascript:void(0);" variant="primary" size="sm">
            <TbFileExport className="me-1" /> Export CSV
          </Button>
        </div>
      </CardHeader>
      <CardBody className="p-0">
        <div className="table-responsive">
          <Table className="table-centered table-custom table-sm table-nowrap table-hover mb-0">
            <tbody>
              {orders.map((order) => (
                <tr key={order.id}>
                  <td>
                    <div className="d-flex align-items-center">
                      <img src={order.userImage} className="avatar-sm rounded-circle me-2" alt={order.userName} />
                      <div>
                        <h5 className="fs-base my-1">
                          <a href="ecommerce-order-details.html" className="text-body">
                            #{order.id}
                          </a>
                        </h5>
                        <span className="text-muted fs-xs">{order.userName}</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span className="text-muted fs-xs">Product</span>
                    <h5 className="fs-base mt-1 fw-normal">{order.product}</h5>
                  </td>
                  <td>
                    <span className="text-muted fs-xs">Date</span>
                    <h5 className="fs-base mt-1 fw-normal">{order.date}</h5>
                  </td>
                  <td>
                    <span className="text-muted fs-xs">Amount</span>
                    <h5 className="fs-base mt-1 fw-normal">{order.amount}</h5>
                  </td>
                  <td>
                    <span className="text-muted fs-xs d-flex align-items-center">Status</span>
                    <h5 className="fs-base mt-1 fw-normal">
                      <TbCircleFilled className={`fs-xs text-${order.statusVariant}`} /> {order.status}
                    </h5>
                  </td>
                  <td style={{ width: 30 }}>
                    <Dropdown>
                      <DropdownToggle as={Link} to="" className="dropdown-toggle text-muted drop-arrow-none card-drop p-0">
                        <TbDotsVertical className="fs-lg" />
                      </DropdownToggle>
                      <DropdownMenu className="dropdown-menu-end">
                        <DropdownItem href="#">View Details</DropdownItem>
                        <DropdownItem href="#">Cancel Order</DropdownItem>
                      </DropdownMenu>
                    </Dropdown>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </CardBody>
      <CardFooter className="border-0">

        <CardPagination totalItems={5} itemsPerPage={5} currentPage={1} itemsName="orders" />

      </CardFooter>
    </Card>
  </Col>
  )
}

export default RecentOrders
