// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/success-mail/success-mail.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-success-mail',
    host: { 'data-component-id': 'auth2-success-mail' },
    imports: [RouterLink],
    templateUrl: './success-mail.component.html',
    styles: ``
})
export class SuccessMailComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                </div>

                                <form>
                                    <div class="mb-4">
                                        <div class="avatar-xxl mx-auto mt-2">
                                            <div
                                                class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                                <img src="assets/images/checkmark.png" alt="dark logo" height="64">
                                            </div>
                                        </div>
                                    </div>

                                    <h4 class="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>


                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-primary fw-semibold py-2">Bake to
                                            Dashboard</button>
                                    </div>
                                </form>

                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span
                                        class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-2/success-mail/index.tsx
import { Button, Card, CardBody, Col, Row } from "react-bootstrap";
import AppLogo from "@/components/AppLogo";
import { author, currentYear } from "@/helpers";
;


import checkmark from '@/assets/images/checkmark.png';

const SuccessMail = () => {
    return (
        <div className="auth-box d-flex align-items-center">
            <div className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <CardBody>
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                        </div>

                                        <form>
                                            <div className="mb-4">
                                                <div className="avatar-xxl mx-auto mt-2">
                                                    <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                                        <img src={checkmark} alt="checkmark" height={64} />
                                                    </div>
                                                </div>
                                            </div>

                                            <h4 className="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>

                                            <div className="d-grid">
                                                <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                                    Back to Dashboard
                                                </Button>
                                            </div>
                                        </form>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by{' '}
                                            <span className="fw-semibold">{author}</span>
                                        </p>
                                    </CardBody>
                                </Col>

                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </div>
        </div>
    )
}

export default SuccessMail
