// src/views/auth/auth-2/two-factor/index.tsx

import AppLogo from "@/components/AppLogo"
import OTPInput from "@/components/OTPInput"
import { author, currentYear } from "@/helpers"
import { Link } from "react-router";
import { useState } from "react"
import { Button, Card, Col, Form, Row } from "react-bootstrap"


const TwoFactor = () => {
    const [code, setCode] = useState<string[]>(Array(6).fill(''));

    return (
        <div className="auth-box d-flex align-items-center">
            <div className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <div className="card-body">
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                            <h4 className="fw-bold mt-4">Request sent Successfully ! | IN+</h4>
                                        </div>

                                        <div className="text-center mb-4">
                                            <h5 className="text-muted fs-base mb-3">
                                                We&apos;ve emailed you a 6-digit verification code we sent to
                                            </h5>
                                            <div className="fw-bold fs-3">******6789</div>
                                        </div>

                                        <Form>
                                            <div className="mb-3">
                                                <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" />
                                            </div>
                                            <div className="d-grid">
                                                <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                                    Confirm
                                                </Button>
                                            </div>
                                        </Form>

                                        <p className="mt-4 text-muted text-center mb-4">
                                            Don’t have a code?{' '}
                                            <Link to="" className="text-decoration-underline link-offset-2 fw-semibold">
                                                Resend
                                            </Link>{' '}
                                            or{' '}
                                            <Link to="" className="text-decoration-underline link-offset-2 fw-semibold">
                                                Call Us
                                            </Link>
                                        </p>

                                        <p className="text-muted text-center mb-0">
                                            Return to{' '}
                                            <Link to="/auth-2/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                                Sign in
                                            </Link>
                                        </p>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by{' '}
                                            <span className="fw-semibold">{author}</span>
                                        </p>
                                    </div>
                                </Col>

                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 rounded-0 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center" />
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </div>
        </div>
    )
}

export default TwoFactor

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/two-factor/two-factor.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgOtpInputComponent } from 'ng-otp-input';

@Component({
  selector: 'app-two-factor',
  host: { 'data-component-id': 'auth2-factor' },
  imports: [RouterLink,NgOtpInputComponent],
  templateUrl: './two-factor.component.html',
  styles: ``
})
export class TwoFactorComponent {
   currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                    <h4 class="fw-bold mt-4">Request sent Successfully ! | IN+</h4>
                                </div>

                                <div class="text-center mb-4">
                                    <h5 class="text-muted fs-base mb-3">We've emailed you a 6-digit verification code we
                                        sent to</h5>

                                    <div class="fw-bold fs-3">******6789</div>
                                </div>

                                <form>
                                    <label class="form-label">Enter your 6-digit code <span
                                            class="text-danger">*</span></label>
                                    <div class="two-factor mb-3">
                                        <ng-otp-input
                                            [config]="{ length: 6, allowNumbersOnly:true, inputClass:'form-control text-center',}">
                                        </ng-otp-input>
                                    </div>

                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                                    </div>
                                </form>

                                <p class="mt-4 text-muted text-center mb-4">Don’t have a code? <a href="javascript:void(0)"
                                        class="text-decoration-underline link-offset-2 fw-semibold">Resend</a> or <a
                                        href="javascript:void(0)" class="text-decoration-underline link-offset-2 fw-semibold">Call Us</a>
                                </p>
                                <p class="text-muted text-center mb-0">
                                    Return to <a routerLink="/auth-2/sign-in"
                                        class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                                </p>

                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
