// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version3/login-pin/login-pin.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgOtpInputComponent } from 'ng-otp-input';

@Component({
    selector: 'app-login-pin',
    host: { 'data-component-id': 'auth3-login-pin' },
    imports: [RouterLink,NgOtpInputComponent],
    templateUrl: './login-pin.component.html',
    styles: ``
})
export class LoginPinComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box p-0 w-100">
    <div class="row w-100 g-0">
        <div class="col">
            <div class="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                <div class="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                </div>
            </div>
        </div>

        <div class="col-xl-auto">
            <div class="card auth-box-form border-0 mb-0">
                <div class="card-body min-vh-100 d-flex flex-column justify-content-center">
                    <div class="auth-brand mb-0 text-center">
                        <a routerLink="/" class="logo-dark">
                            <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a routerLink="/" class="logo-light">
                            <img src="assets/images/logo.png" alt="logo" height="32">
                        </a>
                    </div>

                    <div class="mt-auto text-center">
                        <h4 class="fw-bold">Welcome to IN+</h4>
                        <p class="text-muted mx-auto mb-5">This screen is locked. Enter your PIN to continue.</p>

                        <div class="text-center mb-4">
                            <img src="assets/images/users/user-1.jpg"
                                class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                            <h5 class="fs-md">Damian D.</h5>
                        </div>

                        <form>
                            <label class="form-label d-flex">Enter your 6-digit code <span
                                    class="text-danger">*</span></label>
                            <div class="mb-3 two-factor">
                                <ng-otp-input
                                    [config]="{ length: 6, allowNumbersOnly:true, inputClass:'form-control py-2 bg-light bg-opacity-40 border-light text-center',}">
                                </ng-otp-input>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                            </div>
                        </form>
                    </div>

                    <p class="text-muted text-center mt-4 mb-0">
                        Not you? Return to <a routerLink="/auth-3/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                    </p>

                    <p class="text-center text-muted mt-auto mb-0">
                        © 2014 -
                        {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-3/login-pin/index.tsx

import AppLogo from '@/components/AppLogo';
import OTPInput from '@/components/OTPInput';
import { author, currentYear } from '@/helpers';

import { Link } from "react-router";;
import { useState } from 'react';
import { Button, Card, CardBody, Col, Form, Row } from 'react-bootstrap';

import user1 from '@/assets/images/users/user-1.jpg';


const LoginWithPin = () => {
        const [code, setCode] = useState<string[]>(Array(6).fill(''));
    return (
        <div className="auth-box p-0 w-100">
            <Row className="w-100 g-0">
                <Col>
                    <div className="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                        <div className="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center"></div>
                    </div>
                </Col>

                <Col xl="auto">
                    <Card className="auth-box-form border-0 mb-0">
                        <CardBody className="min-vh-100 d-flex flex-column justify-content-center">
                            <div className="auth-brand mb-0 text-center">
                                <AppLogo />
                            </div>

                            <div className="mt-auto text-center">
                                <h4 className="fw-bold">Welcome to IN+</h4>
                                <p className="text-muted mx-auto mb-5">This screen is locked. Enter your PIN to continue.</p>

                                <div className="text-center mb-4">
                                    <img
                                        src={user1}
                                        className="rounded-circle img-thumbnail avatar-xxl mb-2"
                                        alt="thumbnail"
                                        width={120}
                                        height={120}
                                    />
                                    <h5 className="fs-md">Damian D.</h5>
                                </div>

                                <Form>
                                  <div className='mb-3'>
                                        <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" labelClassName="d-flex" inputClassName="py-2 bg-light bg-opacity-40 border-light" />
                                    </div>

                                    <div className="d-grid">
                                        <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                            Confirm
                                        </Button>
                                    </div>
                                </Form>
                            </div>

                            <p className="text-muted text-center mt-4 mb-0">
                                Not you? Return to{' '}
                                <Link to="/auth-3/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                    Sign in
                                </Link>
                            </p>

                            <p className="text-center text-muted mt-auto mb-0">
                                © 2014 - <span>{currentYear}</span> INSPINIA — by{' '}
                                <span className="fw-semibold">{author}</span>
                            </p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default LoginWithPin;
