// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-1/success-mail/index.tsx
import AppLogo from "@/components/AppLogo"
import { Button, Card, Col, Container, Form, Row } from "react-bootstrap"
import checkmark from '@/assets/images/checkmark.png';

import { author, currentYear } from "@/helpers";

const SuccessMail = () => {
    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">
                            <AppLogo />
                            <h4 className="fw-bold mt-3">Welcome to IN+</h4>
                            <p className="text-muted w-lg-75 mx-auto">
                                Awesome! You&apos;ve read the important message like a pro.
                            </p>
                        </div>

                        <Card className="p-4 rounded-4">
                            <Form>
                                <div className="mb-4">
                                    <div className="avatar-xxl mx-auto mt-2">
                                        <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                            <img src={checkmark} alt="checkmark" height="64" />
                                        </div>
                                    </div>
                                </div>

                                <h4 className="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>

                                <div className="d-grid">
                                    <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                        Back to Dashboard
                                    </Button>
                                </div>
                            </Form>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default SuccessMail

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/success-mail/success-mail.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-success-mail',
    imports: [RouterLink],
    templateUrl: './success-mail.component.html',
    styles: ``
})
export class SuccessMailComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a routerLink="/" class="logo-dark">
                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                    </a>
                    <a routerLink="/" class="logo-light">
                        <img src="assets/images/logo.png" alt="logo" height="32">
                    </a>
                    <h4 class="fw-bold mt-3">Welcome to IN+</h4>
                    <p class="text-muted w-lg-75 mx-auto">Awesome! You’ve read the important message like a pro.</p>
                </div>

                <div class="card p-4 rounded-4">
                    <form>
                        <div class="mb-4">
                            <div class="avatar-xxl mx-auto mt-2">
                                <div
                                    class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                    <img src="assets/images/checkmark.png" alt="dark logo" height="64">
                                </div>
                            </div>
                        </div>

                        <h4 class="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Bake to Dashboard</button>
                        </div>
                    </form>
                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    {{currentYear}} INSPINIA — by <span
                        class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</div>
