// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/delete-account/delete-account.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-delete-account',
  imports: [RouterLink],
  templateUrl: './delete-account.component.html',
  styles: ``
})
export class DeleteAccountComponent {
  currentYear = currentYear
    credits = credits
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a routerLink="/" class="logo-dark">
                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                    </a>
                    <a routerLink="/" class="logo-light">
                        <img src="assets/images/logo.png" alt="logo" height="32">
                    </a>
                </div>

                <div class="card p-4 rounded-4">
                    <div class="mb-4">
                        <div class="avatar-xxl mx-auto mt-2">
                            <div class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                <img src="assets/images/delete.png" alt="dark logo" height="64">
                            </div>
                        </div>
                    </div>

                    <h4 class="fw-bold text-center mb-3">Account Deactivated</h4>
                    <p class="text-muted text-center mb-4">Your account is currently inactive. Reactivate now to regain
                        access to all features and opportunities.</p>

                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary fw-semibold py-2">Reactivate Now</button>
                    </div>

                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</div>

// src/views/auth/auth-1/delete-account/index.tsx
import { Container, Row, Col, Card, Button } from 'react-bootstrap';
import deleteIcon from '@/assets/images/delete.png';
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';

const DeleteAccount = () => {
    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">
                            <AppLogo />
                        </div>

                        <Card className="p-4 rounded-4">
                            <div className="mb-4">
                                <div className="avatar-xxl mx-auto mt-2">
                                    <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle d-flex align-items-center justify-content-center">
                                        <img src={deleteIcon} alt="delete icon" height={64} />
                                    </div>
                                </div>
                            </div>

                            <h4 className="fw-bold text-center mb-3">Account Deactivated</h4>
                            <p className="text-muted text-center mb-4">
                                Your account is currently inactive. Reactivate now to regain access to all features and opportunities.
                            </p>

                            <div className="d-grid">
                                <Button type="button" variant="primary" className="fw-semibold py-2">
                                    Reactivate Now
                                </Button>
                            </div>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    );
};

export default DeleteAccount;
