// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-2/login-pin/index.tsx

import { Button, Card, Col, Form, Row } from 'react-bootstrap';
import { useState } from 'react';
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';

import { Link } from "react-router";;
import OTPInput from '@/components/OTPInput';

import user1 from '@/assets/images/users/user-1.jpg';


const LoginWithPin = () => {
    const [code, setCode] = useState<string[]>(Array(6).fill(''));
    return (
        <div className="auth-box d-flex align-items-center">
            <div className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <div className="card-body">
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                            <h4 className="fw-bold mt-4">Welcome to IN+</h4>
                                            <p className="text-muted w-lg-75 mx-auto">
                                                This screen is locked. Enter your PIN to continue.
                                            </p>
                                        </div>

                                        <div className="text-center mb-4">
                                            <img
                                                src={user1}
                                                alt="thumbnail"
                                                className="rounded-circle img-thumbnail avatar-xxl mb-2"
                                            />
                                            <h5 className="fs-md">Damian D.</h5>
                                        </div>

                                        <Form>
                                            <div className='mb-3'>
                                                <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" />
                                            </div>

                                            <div className="d-grid">
                                                <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                                    Confirm
                                                </Button>
                                            </div>
                                        </Form>

                                        <p className="text-muted text-center mt-4 mb-0">
                                            Not you? Return to{' '}
                                            <Link
                                                to="/auth-2/sign-in"
                                                className="text-decoration-underline link-offset-3 fw-semibold"
                                            >
                                                Sign in
                                            </Link>
                                        </p>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by{' '}
                                            <span className="fw-semibold">{author}</span>
                                        </p>
                                    </div>
                                </Col>

                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </div>
        </div>
    );
};

export default LoginWithPin;

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/login-pin/login-pin.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgOtpInputComponent } from 'ng-otp-input';

@Component({
    selector: 'app-login-pin',
    host: { 'data-component-id': 'auth2-login-pin' },
    imports: [RouterLink,NgOtpInputComponent],
    templateUrl: './login-pin.component.html',
    styles: ``
})
export class LoginPinComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                    <h4 class="fw-bold mt-4">Welcome to IN+</h4>
                                    <p class="text-muted w-lg-75 mx-auto">This screen is locked. Enter your PIN to
                                        continue.</p>
                                </div>

                                <div class="text-center mb-4">
                                    <img src="assets/images/users/user-1.jpg"
                                        class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                                    <h5 class="fs-md">Damian D.</h5>
                                </div>

                                <form>
                                    <label class="form-label">Enter your 6-digit code <span
                                            class="text-danger">*</span></label>
                                    <div class="mb-3 two-factor">
                                        <ng-otp-input
                                            [config]="{ length: 6, allowNumbersOnly:true, inputClass:'form-control text-center',}">
                                        </ng-otp-input>
                                    </div>

                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                                    </div>
                                </form>

                                <p class="text-muted text-center mt-4 mb-0">
                                    Not you? Return to <a routerLink="/auth-2/sign-in"
                                        class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                                </p>

                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
