// rawfiles/src/views/dashboards/dashboard/components/ProductInventory.tsx
import { Button, Card, CardBody, CardFooter, CardHeader, CardTitle, Col, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, Table } from 'react-bootstrap'
import { TbCircleFilled, TbDotsVertical, TbFileExport, TbPlus, TbStar, TbStarFilled, TbStarHalfFilled } from 'react-icons/tb'

import CardPagination from '@/components/cards/CardPagination'
import { products } from '../data'

const renderStars = (rating: number) => {
  const fullStars = Math.floor(rating)
  const halfStar = rating % 1 !== 0
  const emptyStars = 5 - fullStars - (halfStar ? 1 : 0)

  return (
    <span className="text-warning">
      {[...Array(fullStars)].map((_, i) => (
        <TbStarFilled key={`full-${i}`} />
      ))}
      {halfStar && <TbStarHalfFilled />}
      {[...Array(emptyStars)].map((_, i) => (
        <TbStar key={`empty-${i}`} />
      ))}
    </span>
  )
}

const ProductInventory = () => {
  return (
    <Col xxl={6}>
      <Card>
        <CardHeader className="justify-content-between align-items-center border-dashed">
          <CardTitle as="h4" className="mb-0">Product Inventory</CardTitle>
          <div className="d-flex gap-2">
            <Button href="ecommerce-add-product.html" variant="soft-secondary" size="sm">
              <TbPlus className="me-1" /> Add Product
            </Button>
            <Button href="javascript:void(0);" variant="primary" size="sm">
              <TbFileExport className="me-1" /> Export CSV
            </Button>
          </div>
        </CardHeader>
        <CardBody className="p-0">
          <div className="table-responsive">
            <Table className="table-centered table-custom table-sm table-nowrap table-hover mb-0">
              <tbody>
                {products.map((product) => (
                  <tr key={product.id}>
                    <td>
                      <div className="d-flex align-items-center">
                        <img src={product.image} className="avatar-sm rounded-circle me-2" alt={product.name} />
                        <div>
                          <h5 className="fs-base my-1">
                            <a href="ecommerce-product-details.html" className="text-body">
                              {product.name}
                            </a>
                          </h5>
                          <span className="text-muted fs-xs">{product.category}</span>
                        </div>
                      </div>
                    </td>
                    <td>
                      <span className="text-muted fs-xs">Stock</span>
                      <h5 className="fs-base mt-1 fw-normal">{product.stock}</h5>
                    </td>
                    <td>
                      <span className="text-muted fs-xs">Price</span>
                      <h5 className="fs-base mt-1 fw-normal">{product.price}</h5>
                    </td>
                    <td>
                      <span className="text-muted fs-xs">Ratings</span>
                      <h5 className="fs-base mt-1 fw-normal">
                        {renderStars(product.ratings)}
                        <span className="ms-1">
                          <a href="ecommerce-reviews.html" className="link-reset fw-semibold">
                            ({product.reviews})
                          </a>
                        </span>
                      </h5>
                    </td>
                    <td>
                      <span className="text-muted fs-xs">Status</span>
                      <h5 className="fs-base mt-1 fw-normal">
                        <TbCircleFilled className={`fs-xs text-${product.statusVariant}`} /> {product.status}
                      </h5>
                    </td>
                    <td style={{ width: 30 }}>
                      <Dropdown>
                        <DropdownToggle as="a" href="#" className="dropdown-toggle text-muted drop-arrow-none card-drop p-0">
                          <TbDotsVertical className="fs-lg" />
                        </DropdownToggle>
                        <DropdownMenu className="dropdown-menu-end">
                          <DropdownItem href="#">Edit Product</DropdownItem>
                          <DropdownItem href="#">Remove</DropdownItem>
                        </DropdownMenu>
                      </Dropdown>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </CardBody>
        <CardFooter className="border-0">

          <CardPagination totalItems={5} itemsPerPage={5} currentPage={1} itemsName="products" />

        </CardFooter>
      </Card>
    </Col>
  )
}

export default ProductInventory

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/dashboards/dashboard-2/components/product-inventory/product-inventory.component.ts
import {Component} from '@angular/core';
import {RouterLink} from '@angular/router';
import {NgIcon} from '@ng-icons/core';
import {CommonModule} from '@angular/common';
import {currency} from '@/app/constants';
import {NgbDropdown, NgbDropdownItem, NgbDropdownMenu, NgbDropdownToggle} from '@ng-bootstrap/ng-bootstrap';
import {LucideAngularModule} from 'lucide-angular';
import {toTitleCase} from '@/app/utils/string-utils';
import {RatingComponent} from '@app/components/rating.component';
import {products} from '@/app/pages/dashboards/dashboard-2/data';

@Component({
    selector: 'app-product-inventory',
    imports: [
        RouterLink,
        NgIcon,
        CommonModule,
        LucideAngularModule,
        NgbDropdown,
        NgbDropdownToggle,
        NgbDropdownMenu,
        NgbDropdownItem,
        RatingComponent
    ],
    templateUrl: './product-inventory.component.html',
})
export class ProductInventoryComponent {
    products = products
    currency = currency;
    toTitleCase = toTitleCase;
}

<div class="card">
    <div class="card-header justify-content-between align-items-center border-dashed">
        <h4 class="card-title mb-0">Product Inventory</h4>
        <div class="d-flex gap-2">
            <a routerLink="/ecommerce/product/add" class="btn btn-sm btn-soft-secondary">
                <ng-icon name="tablerPlus" class="me-1"/>
                Add Product
            </a>
            <a routerLink="" class="btn btn-sm btn-primary">
                <ng-icon name="tablerFileExport" class="me-1"/>
                Export CSV
            </a>
        </div>
    </div>

    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-centered table-custom table-sm table-nowrap table-hover mb-0">
                <tbody>
                <tr *ngFor="let product of products">
                    <td>
                        <div class="d-flex align-items-center">
                            <img [src]="product.image" alt="" class="avatar-sm rounded-circle me-2">
                            <div>
                                <h5 class="fs-base my-1"><a [routerLink]="product.url"
                                                            class="text-body">{{ product.name }}</a>
                                </h5>
                                <span class="text-muted fs-xs">{{ product.category }}</span>
                            </div>
                        </div>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Stock</span>
                        <h5 class="fs-base mt-1 fw-normal">{{ product.stock }} units</h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Price</span>
                        <h5 class="fs-base mt-1 fw-normal">{{ currency }}{{ product.price }}</h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Ratings</span>
                        <h5 class="fs-base mt-1 fw-normal">

                            <span class="text-warning">
                             <app-rating [rate]="product.ratings" [readonly]="true"></app-rating>
                            </span>
                            <span class="ms-1">
                                <a routerLink="/ecommerce/reviews"
                                   class="link-reset fw-semibold">({{ product.reviews }})</a></span>
                        </h5>
                    </td>
                    <td>
                        <span class="text-muted fs-xs">Status</span>
                        <h5 class="fs-base mt-1 fw-normal">
                            <ng-icon name="tablerCircleFill"
                                     [class]="`fs-xs text-${product.variant}`"/>
                            {{ toTitleCase(product.status) }}
                        </h5>
                    </td>
                    <td style="width: 30px;">
                        <div ngbDropdown class="dropdown">
                            <button ngbDropdownToggle
                                    class="dropdown-toggle text-muted drop-arrow-none card-drop p-0 bg-transparent border-0">
                                <ng-icon name="tablerDotsVertical" class="fs-lg"/>
                            </button>
                            <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
                                <a routerLink="" ngbDropdownItem class="dropdown-item">Edit Product</a>
                                <a routerLink="" ngbDropdownItem class="dropdown-item">Remove</a>
                            </div>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>

    <div class="card-footer border-0">
        <div class="align-items-center justify-content-between row text-center text-sm-start">
            <div class="col-sm">
                <span class="text-muted">Showing <span
                    class="fw-semibold">1</span> to <span class="fw-semibold">5</span> of <span
                    class="fw-semibold">10</span> products
                </span>
            </div>
            <div class="col-sm-auto mt-3 mt-sm-0">
                <ul class="pagination pagination-boxed mb-0 justify-content-center">
                    <li class="page-item disabled">
                        <a routerLink="" class="page-link">
                            <ng-icon name="tablerChevronLeft"/>
                        </a>
                    </li>
                    <li class="page-item active">
                        <a routerLink="" class="page-link">1</a>
                    </li>
                    <li class="page-item">
                        <a routerLink="" class="page-link">2</a>
                    </li>
                    <li class="page-item disabled">
                        <a routerLink="" class="page-link">
                            <ng-icon name="tablerChevronRight"/>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
