// rawfiles/src/layouts/components/customizer/index.tsx
import {Fragment} from "react";
import {Button, Col, Offcanvas, Row} from "react-bootstrap";
import SimpleBar from 'simplebar-react';
import {useLayoutContext} from "@/context/useLayoutContext";

import type {
    LayoutOrientationType,
    LayoutPositionType,
    LayoutSkinType,
    LayoutThemeType,
    SideNavType,
    TopBarType
} from "@/types/layout";
import {toPascalCase} from "@/helpers/casing";
import {TbX} from "react-icons/tb";


import pattern from "@/assets/images/user-bg-pattern.png"

import classicImg from "@/assets/images/layouts/themes/theme-classic.png";
import materialImg from "@/assets/images/layouts/themes/theme-material.png";
import modernImg from "@/assets/images/layouts/themes/theme-modern.png";
import saasImg from "@/assets/images/layouts/themes/theme-saas.png";
import flatImg from "@/assets/images/layouts/themes/theme-flat.png";
import minimalImg from "@/assets/images/layouts/themes/theme-minimal.png";
import galaxyImg from "@/assets/images/layouts/themes/theme-galaxy.png";

import light from "@/assets/images/layouts/light.svg";
import lightSideNavImg from "@/assets/images/layouts/light.svg";
import dark from "@/assets/images/layouts/dark.svg";
import system from "@/assets/images/layouts/system.svg";

import lightTopBarImg from "@/assets/images/layouts/topbar-light.svg";
import darkTopBarImg from "@/assets/images/layouts/topbar-dark.svg";
import grayTopBarImg from "@/assets/images/layouts/topbar-gray.svg";
import gradientTopBarImg from "@/assets/images/layouts/topbar-gradient.svg";
import darkSideNavImg from "@/assets/images/layouts/side-dark.svg";
import graySideNavImg from "@/assets/images/layouts/side-gray.svg";
import gradientSideNavImg from "@/assets/images/layouts/side-gradient.svg";
import imageSideNavImg from "@/assets/images/layouts/side-image.svg";

import compactSideNavImg from "@/assets/images/layouts/sidebar-compact.svg";
import smallSideNavImg from "@/assets/images/layouts/sidebar-sm.svg";
import fullSideNavImg from "@/assets/images/layouts/sidebar-full.svg";

type SkinOptionType = {
    skin: LayoutSkinType;
    image: string;
    disabled?: boolean;
};

type ThemeOptionType = {
    theme: LayoutThemeType;
    image: string;
};

type OrientationOptionType = {
    orientation: LayoutOrientationType;
    image: string;
};

type TopBarColorOptionType = {
    color: TopBarType['color'];
    image: string;
};

type SideNavColorOptionType = {
    color: SideNavType['color'];
    image: string;
};

type SideNavSizeOptionType = {
    label: string;
    size: SideNavType['size'];
    image: string;
};

const skinOptions: SkinOptionType[] = [
    {skin: "classic", image: classicImg},
    {skin: "material", image: materialImg},
    {skin: "modern", image: modernImg},
    {skin: "saas", image: saasImg},
    {skin: "flat", image: flatImg},
    {skin: "minimal", image: minimalImg},
    {skin: "galaxy", image: galaxyImg, disabled: true}
]

const themeOptions: ThemeOptionType[] = [
    {theme: "light", image: light},
    {theme: "dark", image: dark},
    {theme: "system", image: system},
];

const orientationOptions: OrientationOptionType[] = [
    {orientation: "vertical", image: darkSideNavImg},
    {orientation: "horizontal", image: fullSideNavImg},
];

const topBarColorOptions: TopBarColorOptionType[] = [
    {color: "light", image: lightTopBarImg},
    {color: "dark", image: darkTopBarImg},
    {color: "gray", image: grayTopBarImg},
    {color: "gradient", image: gradientTopBarImg},
];

const sidenavColorOptions: SideNavColorOptionType[] = [
    {color: "light", image: lightSideNavImg},
    {color: "dark", image: darkSideNavImg},
    {color: "gray", image: graySideNavImg},
    {color: "gradient", image: gradientSideNavImg},
    {color: "image", image: imageSideNavImg},
];

const sidenavSizeOptions: SideNavSizeOptionType[] = [
    {size: "default", image: lightSideNavImg, label: "Default"},
    {size: "compact", image: compactSideNavImg, label: "Compact"},
    {size: "condensed", image: smallSideNavImg, label: "Condensed"},
    {size: "on-hover", image: smallSideNavImg, label: "On Hover"},
    {size: "on-hover-active", image: lightSideNavImg, label: "On Hover - Show"},
    {size: "offcanvas", image: fullSideNavImg, label: "Offcanvas"},
];

const layoutPositionOptions: { position: LayoutPositionType }[] = [
    {position: "fixed"},
    {position: "scrollable"},
];

const Customizer = () => {

    const {
        customizer,
        skin,
        changeSkin,
        theme,
        changeTheme,
        orientation,
        changeOrientation,
        topBar,
        changeTopBarColor,
        sidenav,
        changeSideNavColor,
        changeSideNavSize,
        position, changeLayoutPosition, toggleSideNavUser, reset
    } = useLayoutContext()

    return (
        <Offcanvas show={customizer.isOpen} onHide={customizer.toggle} placement="end" className="overflow-hidden">
            <div className="d-flex justify-content-between text-bg-primary gap-2 p-3"
                 style={{backgroundImage: `url(${pattern})`}}>
                <div>
                    <h5 className="mb-1 fw-bold text-white text-uppercase">Admin Customizer</h5>
                    <p className="text-white text-opacity-75 fst-italic fw-medium mb-0">Easily configure layout, styles,
                        and preferences for your admin interface.</p>
                </div>

                <div className="flex-grow-0">
                    <button onClick={customizer.toggle} type="button"
                            className="d-block btn btn-sm bg-white bg-opacity-25 text-white rounded-circle btn-icon">
                        <TbX className="fs-lg"/>
                    </button>
                </div>
            </div>

            <SimpleBar className="offcanvas-body p-0 h-100">
                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Select Theme</h5>
                    <Row className="g-3">
                        {
                            skinOptions.map((item, idx) => (
                                <Col sm={6} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`skin-${item.skin}`} className="form-check-input" type="radio"
                                               name="data-skin"
                                               disabled={item.disabled ?? false}
                                               value={item.skin}
                                               checked={skin === item.skin}
                                               onChange={() => changeSkin(item.skin)}/>
                                        <label className="form-check-label p-0 w-100" htmlFor={`skin-${item.skin}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={167.5} height={111.66}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{toPascalCase(item.skin)}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Color Scheme</h5>
                    <Row className="g-3">
                        {
                            themeOptions.map((item, idx) => (
                                <Col sm={4} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`theme-${item.theme}`} className="form-check-input" type="radio"
                                               name="data-bs-theme"
                                               value={item.theme}
                                               checked={theme === item.theme}
                                               onChange={() => changeTheme(item.theme)}/>
                                        <label className="form-check-label p-0 w-100" htmlFor={`theme-${item.theme}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={104.33} height={83.45}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{toPascalCase(item.theme)}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Topbar Color</h5>
                    <Row className="g-3">
                        {
                            topBarColorOptions.map((item, idx) => (
                                <Col sm={4} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`topbar-color-${item.color}`} className="form-check-input"
                                               type="radio"
                                               name="data-topbar-color"
                                               value={item.color}
                                               checked={topBar.color === item.color}
                                               onChange={() => changeTopBarColor(item.color)}/>
                                        <label className="form-check-label p-0 w-100"
                                               htmlFor={`topbar-color-${item.color}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={104.33} height={83.45}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{toPascalCase(item.color)}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Orientation</h5>
                    <Row className="g-3">
                        {
                            orientationOptions.map((item, idx) => (
                                <Col sm={4} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`layout-${item.orientation}`} className="form-check-input"
                                               type="radio"
                                               name="data-layout"
                                               value={item.orientation}
                                               checked={orientation === item.orientation}
                                               onChange={() => changeOrientation(item.orientation)}/>
                                        <label className="form-check-label p-0 w-100"
                                               htmlFor={`layout-${item.orientation}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={104.33} height={83.45}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{toPascalCase(item.orientation)}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Sidenav Color</h5>
                    <Row className="g-3">
                        {
                            sidenavColorOptions.map((item, idx) => (
                                <Col sm={4} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`sidenav-color-${item.color}`} className="form-check-input"
                                               type="radio"
                                               name="data-menu-color"
                                               value={item.color}
                                               checked={sidenav.color === item.color}
                                               onChange={() => changeSideNavColor(item.color)}/>
                                        <label className="form-check-label p-0 w-100"
                                               htmlFor={`sidenav-color-${item.color}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={104.33} height={83.45}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{toPascalCase(item.color)}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <h5 className="mb-3 fw-bold">Sidebar Size</h5>
                    <Row className="g-3">
                        {
                            sidenavSizeOptions.map((item, idx) => (
                                <Col sm={4} key={idx}>
                                    <div className="form-check card-radio">
                                        <input id={`sidenav-size-${item.size}`} className="form-check-input"
                                               type="radio"
                                               name="data-sidenav-size"
                                               value={item.size}
                                               checked={sidenav.size === item.size}
                                               onChange={() => changeSideNavSize(item.size)}/>
                                        <label className="form-check-label p-0 w-100"
                                               htmlFor={`sidenav-size-${item.size}`}>
                                            <img src={item.image} alt="layout-img" className="img-fluid"
                                                   width={104.33} height={83.45}/>
                                        </label>
                                    </div>
                                    <h5 className="text-center text-muted mt-2 mb-0">{item.label}</h5>
                                </Col>
                            ))
                        }
                    </Row>
                </div>

                <div className="p-3 border-bottom border-dashed">
                    <div className="d-flex justify-content-between align-items-center">
                        <h5 className="fw-bold mb-0">Layout Position</h5>

                        <div className="btn-group radio" role="group">
                            {
                                layoutPositionOptions.map((item, idx) => (
                                    <Fragment key={idx}>
                                        <input type="radio" className="btn-check" name="data-layout-position"
                                               id={`position-${item.position}`}
                                               value={item.position}
                                               checked={position === item.position}
                                               onChange={() => changeLayoutPosition(item.position)}/>
                                        <label className="btn btn-sm btn-soft-warning w-sm"
                                               htmlFor={`position-${item.position}`}>{toPascalCase(item.position)}</label>
                                    </Fragment>
                                ))
                            }
                        </div>
                    </div>
                </div>

                <div className="p-3">
                    <div className="d-flex justify-content-between align-items-center">
                        <h5 className="mb-0"><label className="fw-bold m-0" htmlFor="sidebaruser-check">Sidebar User
                            Info</label></h5>

                        <div className="form-check form-switch fs-lg">
                            <input type="checkbox" className="form-check-input" name="sidebar-user"
                                   checked={sidenav.user}
                                   onChange={toggleSideNavUser}/>
                        </div>
                    </div>
                </div>
            </SimpleBar>

            <div className="offcanvas-footer border-top p-3 text-center">
                <Row>
                    <Col sm={6}>
                        <Button variant="light" type="button" onClick={reset}
                                className="fw-semibold py-2 w-100">Reset</Button>
                    </Col>
                    <Col sm={6}>
                        <a href="https://wrapbootstrap.com/theme/inspinia-multipurpose-admin-dashboard-template-WB0R5L90S?ref=inspinia"
                           target="_blank" className="btn btn-danger bg-gradient py-2 fw-semibold w-100">Buy Now</a>
                    </Col>
                </Row>
            </div>
        </Offcanvas>
    )
}

export default Customizer

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/customizer/customizer.component.ts
import {Component} from '@angular/core';
import {NgbActiveOffcanvas} from '@ng-bootstrap/ng-bootstrap';
import {SimplebarAngularModule} from 'simplebar-angular';
import {NgIcon, provideIcons} from '@ng-icons/core';
import {tablerX} from "@ng-icons/tabler-icons"
import {LayoutStoreService} from '@core/services/layout-store.service';
import {
    LayoutOrientationType,
    LayoutPositionType,
    LayoutSkinType,
    LayoutThemeType,
    SideNavType,
    TopBarType
} from '@/app/types/layout';
import {CommonModule} from '@angular/common';
import {toPascalCase} from '@/app/utils/string-utils';

const classicImg = "assets/images/layouts/themes/theme-classic.png";
const materialImg = "assets/images/layouts/themes/theme-material.png";
const modernImg = "assets/images/layouts/themes/theme-modern.png";
const saasImg = "assets/images/layouts/themes/theme-saas.png";
const flatImg = "assets/images/layouts/themes/theme-flat.png";
const minimalImg = "assets/images/layouts/themes/theme-minimal.png";
const galaxyImg = "assets/images/layouts/themes/theme-galaxy.png";

const light = "assets/images/layouts/light.svg";
const dark = "assets/images/layouts/dark.svg";
const system = "assets/images/layouts/system.svg";

const lightTopBarImg = "assets/images/layouts/topbar-light.svg";
const darkTopBarImg = "assets/images/layouts/topbar-dark.svg";
const grayTopBarImg = "assets/images/layouts/topbar-gray.svg";
const gradientTopBarImg = "assets/images/layouts/topbar-gradient.svg";

const lightSideNavImg = "assets/images/layouts/light.svg";
const darkSideNavImg = "assets/images/layouts/side-dark.svg";
const graySideNavImg = "assets/images/layouts/side-gray.svg";
const gradientSideNavImg = "assets/images/layouts/side-gradient.svg";
const imageSideNavImg = "assets/images/layouts/side-image.svg";

const compactSideNavImg = "assets/images/layouts/sidebar-compact.svg";
const smallSideNavImg = "assets/images/layouts/sidebar-sm.svg";
const fullSideNavImg = "assets/images/layouts/sidebar-full.svg";

type SkinOptionType = {
    skin: LayoutSkinType;
    image: string;
    disabled?: boolean;
};

type ThemeOptionType = {
    theme: LayoutThemeType;
    image: string;
};

type OrientationOptionType = {
    orientation: LayoutOrientationType;
    image: string;
};

type TopBarColorOptionType = {
    color: TopBarType['color'];
    image: string;
};

type SideNavColorOptionType = {
    color: SideNavType['color'];
    image: string;
};

type SideNavSizeOptionType = {
    label: string;
    size: SideNavType['size'];
    image: string;
};

@Component({
    selector: 'app-customizer',
    imports: [SimplebarAngularModule, NgIcon, CommonModule],
    templateUrl: './customizer.component.html',
    viewProviders: [provideIcons({tablerX})]
})
export class CustomizerComponent {
    constructor(public activeOffcanvas: NgbActiveOffcanvas, public layout: LayoutStoreService) {
    }

    close(): void {
        this.activeOffcanvas.close();
    }

    skinOptions: SkinOptionType[] = [
        {skin: "classic", image: classicImg},
        {skin: "material", image: materialImg},
        {skin: "modern", image: modernImg},
        {skin: "saas", image: saasImg},
        {skin: "flat", image: flatImg},
        {skin: "minimal", image: minimalImg},
        {skin: "galaxy", image: galaxyImg, disabled: true}
    ]

    themeOptions: ThemeOptionType[] = [
        {theme: "light", image: light},
        {theme: "dark", image: dark},
        {theme: "system", image: system},
    ];

    orientationOptions: OrientationOptionType[] = [
        {orientation: "vertical", image: darkSideNavImg},
        {orientation: "horizontal", image: fullSideNavImg},
    ];

    topBarColorOptions: TopBarColorOptionType[] = [
        {color: "light", image: lightTopBarImg},
        {color: "dark", image: darkTopBarImg},
        {color: "gray", image: grayTopBarImg},
        {color: "gradient", image: gradientTopBarImg},
    ];

    sidenavColorOptions: SideNavColorOptionType[] = [
        {color: "light", image: lightSideNavImg},
        {color: "dark", image: darkSideNavImg},
        {color: "gray", image: graySideNavImg},
        {color: "gradient", image: gradientSideNavImg},
        {color: "image", image: imageSideNavImg},
    ];

    sidenavSizeOptions: SideNavSizeOptionType[] = [
        {size: "default", image: lightSideNavImg, label: "Default"},
        {size: "compact", image: compactSideNavImg, label: "Compact"},
        {size: "condensed", image: smallSideNavImg, label: "Condensed"},
        {size: "on-hover", image: smallSideNavImg, label: "On Hover"},
        {size: "on-hover-active", image: lightSideNavImg, label: "On Hover - Show"},
        {size: "offcanvas", image: fullSideNavImg, label: "Offcanvas"},
    ];

    layoutPositionOptions: { position: LayoutPositionType }[] = [
        {position: "fixed"},
        {position: "scrollable"},
    ];
    protected readonly toPascalCase = toPascalCase;
}

<div class="d-flex justify-content-between text-bg-primary gap-2 p-3"
     style="background-image: url(assets/images/user-bg-pattern.png);">
    <div>
        <h5 class="mb-1 fw-bold text-white text-uppercase">Admin Customizer</h5>
        <p class="text-white text-opacity-75 fst-italic fw-medium mb-0">Easily configure layout, styles, and preferences
            for
            your admin interface.</p>
    </div>

    <div class="flex-grow-0">
        <button (click)="close()" type="button"
                class="d-block btn btn-sm bg-white bg-opacity-25 text-white rounded-circle btn-icon">
            <ng-icon name="tablerX" class="fs-lg"/>
        </button>
    </div>
</div>

<ngx-simplebar class="offcanvas-body p-0 h-100" style="max-height: 80vh">
    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Select Theme</h5>
        <div class="row g-3">
            <div *ngFor="let item of skinOptions" class="col-6">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-skin" [id]="`skin-${item.skin}`"
                           [value]="item.skin"
                           [checked]="layout.skin === item.skin" (change)="layout.setSkin(item.skin)"
                           [disabled]="item.disabled">
                    <label class="form-check-label p-0 w-100" [for]="`skin-${item.skin}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ toPascalCase(item.skin) }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Color Scheme</h5>
        <div class="row">
            <div *ngFor="let item of themeOptions" class="col-4">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-bs-theme" [id]="`theme-${item.theme}`"
                           [value]="item.theme"
                           [checked]="layout.theme === item.theme" (change)="layout.setTheme(item.theme)">
                    <label class="form-check-label p-0 w-100" [for]="`theme-${item.theme}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ toPascalCase(item.theme) }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Orientation</h5>
        <div class="row">
            <div *ngFor="let item of orientationOptions" class="col-4">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-layout" [id]="`orientation-${item.orientation}`"
                           [value]="item.orientation"
                           [checked]="layout.orientation === item.orientation" (change)="layout.setLayoutOrientation(item.orientation)">
                    <label class="form-check-label p-0 w-100" [for]="`orientation-${item.orientation}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ toPascalCase(item.orientation) }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Topbar Color</h5>

        <div class="row g-3">
            <div *ngFor="let item of topBarColorOptions" class="col-4">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-topbar-color"
                           [id]="`topbar-color-${item.color}`"
                           [value]="item.color"
                           [checked]="layout.topbarColor === item.color" (change)="layout.setTopbarColor(item.color)">
                    <label class="form-check-label p-0 w-100" [for]="`topbar-color-${item.color}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ toPascalCase(item.color) }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Sidenav Color</h5>

        <div class="row g-3">
            <div *ngFor="let item of sidenavColorOptions" class="col-4">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-menu-color"
                           [id]="`sidenav-color-${item.color}`"
                           [value]="item.color"
                           [checked]="layout.sidenavColor === item.color" (change)="layout.setSidenavColor(item.color)">
                    <label class="form-check-label p-0 w-100" [for]="`sidenav-color-${item.color}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ toPascalCase(item.color) }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <h5 class="mb-3 fw-bold">Sidebar Size</h5>

        <div class="row g-3">
            <div *ngFor="let item of sidenavSizeOptions" class="col-4">
                <div class="form-check card-radio">
                    <input class="form-check-input" type="radio" name="data-sidenav-size"
                           [id]="`sidenav-size-${item.size}`"
                           [value]="item.size"
                           [checked]="layout.sidenavSize === item.size" (change)="layout.setSidenavSize(item.size)">
                    <label class="form-check-label p-0 w-100" [for]="`sidenav-size-${item.size}`">
                        <img [src]="item.image" alt="layout-img" class="img-fluid">
                    </label>
                </div>
                <h5 class="text-center text-muted mt-2 mb-0">{{ item.label }}</h5>
            </div>
        </div>
    </div>

    <div class="p-3 border-bottom border-dashed">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="fw-bold mb-0">Layout Position</h5>

            <div class="btn-group radio" role="group">
                <ng-container *ngFor="let item of layoutPositionOptions">
                    <input type="radio" class="btn-check" name="data-layout-position"
                           [id]="`layout-position-${item.position}`"
                           [value]="item.position"
                           [checked]="layout.position === item.position"
                           (change)="layout.setLayoutPosition(item.position)">
                    <label class="btn btn-sm btn-soft-warning w-sm"
                           [for]="`layout-position-${item.position}`">{{ toPascalCase(item.position) }}</label>
                </ng-container>
            </div>
        </div>
    </div>

    <div class="p-3">
        <div class="d-flex justify-content-between align-items-center">
            <h5 class="mb-0"><label class="fw-bold m-0" for="sidebaruser-check">Sidebar User Info</label></h5>

            <div class="form-check form-switch fs-lg">
                <input type="checkbox" class="form-check-input" name="sidebar-user" [checked]="layout.sidenavUser"
                       (change)="layout.toggleSidenavUser()">
            </div>
        </div>
    </div>
</ngx-simplebar>

<div class="offcanvas-footer border-top p-3 text-center">
    <div class="row">
        <div class="col-6">
            <button (click)="layout.reset()" type="button" class="btn btn-light fw-semibold py-2 w-100"
                    id="reset-layout">
                Reset
            </button>
        </div>
        <div class="col-6">
            <a href="https://wrapbootstrap.com/theme/inspinia-multipurpose-admin-dashboard-template-WB0R5L90S?ref=inspinia"
               target="_blank" class="btn btn-danger bg-gradient py-2 fw-semibold w-100">Buy Now</a>
        </div>
    </div>
</div>
