// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/other-pages/maintenance/maintenance.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-maintenance',
  imports: [RouterLink],
  templateUrl: './maintenance.component.html',
  styles: ``
})
export class MaintenanceComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-6">
                <div class="card mb-0 rounded-4">
                    <div class="card-body">
                        <div class="auth-brand text-center mb-0">
                            <a routerLink="/" class="logo-dark">
                                <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                            </a>
                            <a routerLink="/" class="logo-light">
                                <img src="assets/images/logo.png" alt="logo" height="32">
                            </a>
                        </div>

                        <div class="p-2 text-center">
                            <div class="w-md-50 mx-auto">
                                <img src="assets/images/svg/maintenance.svg" alt="Maintenance" class="img-fluid">
                            </div>

                            <h3 class="fw-bold text-uppercase">Site Under Maintenance</h3>
                            <p class="text-muted">We’re currently performing scheduled maintenance.
                                <br>Please check back soon.
                            </p>

                            <button class="btn btn-primary mt-3 rounded-pill me-1">Call Now</button>
                            <button class="btn btn-info mt-3 rounded-pill">Email Us</button>
                        </div>

                        <p class="text-center text-muted mt-5 mb-0">
                            © 2014 -
                           {{currentYear}} INSPINIA — by <span
                                class="fw-bold">{{credits.name}}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// src/views/other/maintenance/index.tsx
import AppLogo from "@/components/AppLogo"
import { Button, Card, CardBody, Col, Container, Row } from "react-bootstrap"

import { author, currentYear } from "@/helpers"

import maintenanceImg from '@/assets/images/svg/maintenance.svg'

const Maintenance = () => {
    return (
        <div className="auth-box d-flex align-items-center">
            <Container fluid="xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={6}>
                        <Card className="mb-0 rounded-4">
                            <CardBody>
                                <div className="auth-brand text-center mb-0">
                                    <AppLogo />
                                </div>

                                <div className="p-2 text-center">
                                    <div className="w-md-50 mx-auto">
                                        <img
                                            src={maintenanceImg}
                                            alt="Maintenance"
                                            className="img-fluid"
                                        />
                                    </div>

                                    <h3 className="fw-bold text-uppercase">Site Under Maintenance</h3>
                                    <p className="text-muted">
                                        We’re currently performing scheduled maintenance.
                                        <br />
                                        Please check back soon.
                                    </p>

                                    <Button variant="primary"  className="mt-3 rounded-pill me-1">Call Now</Button>
                                    <Button variant="info" className="mt-3 rounded-pill">Email Us</Button>
                                </div>

                                <p className="text-center text-muted mt-5 mb-0">
                                    © 2014 - {currentYear} INSPINIA — by{' '}
                                    <span className="fw-bold">{author}</span>
                                </p>
                            </CardBody>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default Maintenance
