// src_old/views/layouts/boxed/index.tsx

import {Fragment, useEffect} from "react";
import {Alert, Col, Container, Row} from "react-bootstrap";
import PageBreadcrumb from "@/components/PageBreadcrumb";
import {useLayoutContext} from "@/context/useLayoutContext";
import {TbInfoCircle} from "react-icons/tb";

const Page = () => {

    const {changeLayoutWidth, changeSideNavSize, reset} = useLayoutContext()

    useEffect(() => {
        changeLayoutWidth('boxed')
        changeSideNavSize('on-hover')

        return () => reset()
    }, [])

    return (
        <Fragment>

            <Container fluid>
                <PageBreadcrumb title="Boxed"/>
            </Container>

            <Container fluid="xl">
                <Row>
                    <Col sm={12}>
                        <Alert variant="info"
                               className="alert-bordered border-start border-info d-flex align-items-start gap-2">
                            <TbInfoCircle className="fs-xxl"/>
                            <div>
                                To enable the boxed layout, add <code>data-layout-width="boxed"</code> to
                                the <code>&lt;html&gt;</code> tag. For optimal spacing and usability, we also recommend
                                adding <code>data-sidenav-size="on-hover"</code> to make the sidebar compact while
                                keeping more
                                room for content. To apply this dynamically,
                                use <code> changeLayoutWidth('boxed')</code> and <code>changeSideNavSize('on-hover')</code> from
                                the <code>LayoutContext</code>.
                            </div>
                        </Alert>
                    </Col>
                </Row>
            </Container>
        </Fragment>
    )
}

export default Page

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/layouts/boxed/boxed.component.ts
import {Component, inject, OnDestroy, OnInit} from '@angular/core';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {NgIcon} from '@ng-icons/core';
import {NgbAlert} from '@ng-bootstrap/ng-bootstrap';
import {PageTitleComponent} from '@app/components/page-title.component';

@Component({
    selector: 'app-boxed',
    imports: [
        NgIcon,
        NgbAlert,
        PageTitleComponent
    ],
    templateUrl: './boxed.component.html',
})
export class BoxedComponent implements OnInit, OnDestroy {

    layout = inject(LayoutStoreService)

    ngOnInit() {
        this.layout.setLayoutWidth('boxed')
        this.layout.setSidenavSize('on-hover')
    }

    ngOnDestroy() {
        this.layout.reset()
    }
}

<div class="container-fluid">
    <app-page-title title="Compact"/>

    <div class="row">
        <div class="col-12">
            <ngb-alert type="info" class="alert-bordered border-start border-info d-flex align-items-start gap-2">
                <ng-icon name="tablerInfoCircle" class="fs-xxl"/>
                <div>
                    To enable the boxed layout, add
                    <code>data-layout-width="boxed"</code> to the
                    <code>&lt;html&gt;</code> tag. For optimal spacing and usability, we also recommend adding
                    <code>data-sidenav-size="on-hover"</code> to make the sidebar compact while keeping more room for
                    content. You can apply this dynamically using the
                    <code>LayoutStoreService</code> with
                    <code>setLayoutWidth('boxed')</code> and <code>setSidenavSize('on-hover')</code> respectively.
                </div>
            </ngb-alert>
        </div>
    </div>
</div>
