// src_old/views/auth/auth-1/two-factor/index.tsx

import AppLogo from "@/components/AppLogo"
import OTPInput from "@/components/OTPInput"
import { author, currentYear } from "@/helpers"
import { Link } from "react-router";
import { useState } from "react"
import { Button, Card, Col, Container, Form, Row } from "react-bootstrap"


const TwoFactor = () => {
    const [code, setCode] = useState<string[]>(Array(6).fill(''));

    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">
                            <AppLogo />
                            <h4 className="fw-bold mt-3">Two-Factor Verification ! | IN+</h4>
                            <p className="text-muted w-lg-75 mx-auto">
                                Let&apos;s get you signed in. Enter your PIN to continue
                            </p>
                        </div>

                        <Card className="p-4 rounded-4">
                            <div className="text-center mb-4">
                                <h5 className="text-muted fs-base mb-3">
                                    We&apos;ve emailed you a 6-digit verification code we sent to
                                </h5>
                                <div className="fw-bold fs-3">******6789</div>
                            </div>

                            <Form>
                                <div className="mb-3">
                                    <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" />
                                </div>


                                <div className="d-grid">
                                    <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                        Confirm
                                    </Button>
                                </div>
                            </Form>

                            <p className="mt-4 text-muted text-center mb-4">
                                Don’t have a code?&nbsp;
                                <Link to="" className="text-decoration-underline link-offset-2 fw-semibold">
                                    Resend&nbsp;
                                </Link>
                                or
                                <Link to="" className="text-decoration-underline link-offset-2 fw-semibold">
                                    &nbsp;Call Us
                                </Link>
                            </p>

                            <p className="text-muted text-center mb-0">
                                Return to{' '}
                                <Link to="/auth-1/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                    Sign in
                                </Link>
                            </p>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default TwoFactor

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/two-factor/two-factor.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgOtpInputComponent } from 'ng-otp-input';

@Component({
  selector: 'app-two-factor',
  imports: [RouterLink,NgOtpInputComponent],
  templateUrl: './two-factor.component.html',
  styles: ``
})
export class TwoFactorComponent {
   currentYear = currentYear
    credits = credits
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a routerLink="/" class="logo-dark">
                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                    </a>
                    <a routerLink="/" class="logo-light">
                        <img src="assets/images/logo.png" alt="logo" height="32">
                    </a>
                    <h4 class="fw-bold mt-3">Two-Factor Verification ! | IN+</h4>
                    <p class="text-muted w-lg-75 mx-auto">Let’s get you signed in. Enter your PIN to continue</p>
                </div>

                <div class="card p-4 rounded-4">
                    <div class="text-center mb-4">
                        <h5 class="text-muted fs-base mb-3">We've emailed you a 6-digit verification code we sent to
                        </h5>

                        <div class="fw-bold fs-3">******6789</div>
                    </div>

                    <form>
                        <label class="form-label">Enter your 6-digit code <span class="text-danger">*</span></label>
                        <ng-otp-input
                            [config]="{ length: 6, allowNumbersOnly:true, inputClass:'form-control text-center',}">
                        </ng-otp-input>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                        </div>
                    </form>

                    <p class="mt-4 text-muted text-center mb-4">Don’t have a code? <a href="javascript:void(0)"
                            class="text-decoration-underline link-offset-2 fw-semibold">Resend</a> or <a routerLink="#"
                            class="text-decoration-underline link-offset-2 fw-semibold">Call Us</a></p>
                    <p class="text-muted text-center mb-0">
                        Return to <a routerLink="/auth/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                    </p>
                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</div>
