// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version3/success-mail/success-mail.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-success-mail',
    host: { 'data-component-id': 'auth3-success-mail' },
    imports: [RouterLink],
    templateUrl: './success-mail.component.html',
    styles: ``
})
export class SuccessMailComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box p-0 w-100">
    <div class="row w-100 g-0">
        <div class="col">
            <div class="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                <div class="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                </div>
            </div>
        </div>

        <div class="col-xl-auto">
            <div class="card auth-box-form border-0 mb-0">
                <div class="card-body min-vh-100 d-flex flex-column justify-content-center">
                    <div class="auth-brand mb-0 text-center">
                        <a routerLink="/" class="logo-dark">
                            <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a routerLink="/" class="logo-light">
                            <img src="assets/images/logo.png" alt="logo" height="32">
                        </a>
                    </div>

                    <div class="mt-auto text-center">
                        <form>
                            <div class="mb-4">
                                <div class="avatar-xxl mx-auto mt-2">
                                    <div
                                        class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                        <img src="assets/images/checkmark.png" alt="dark logo" height="64">
                                    </div>
                                </div>
                            </div>

                            <h4 class="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Bake to
                                    Dashboard</button>
                            </div>
                        </form>
                    </div>

                    <p class="text-muted text-center mt-4 mb-0">
                        Return to <a routerLink="/auth-3/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                    </p>

                    <p class="text-center text-muted mt-auto mb-0">
                        © 2014 -
                        {{currentYear}} INSPINIA — by <span
                            class="fw-semibold">{{credits.name}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-3/success-mail/index.tsx
import { Button, Card, CardBody, Col, Form, Row } from "react-bootstrap";
import AppLogo from "@/components/AppLogo";
import { author, currentYear } from "@/helpers";
;


import checkmark from '@/assets/images/checkmark.png';
import { Link } from "react-router";

const SuccessMail = () => {
    return (
        <div className="auth-box p-0 w-100">
            <Row className="w-100 g-0">
                <Col>
                    <div className="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                        <div className="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center"></div>
                    </div>
                </Col>

                <Col xl="auto">
                    <Card className="auth-box-form border-0 mb-0">
                        <CardBody className="min-vh-100 d-flex flex-column justify-content-center">
                            <div className="auth-brand mb-0 text-center">
                                <AppLogo />
                            </div>

                            <div className="mt-auto text-center">
                                <Form>
                                    <div className="mb-4">
                                        <div className="avatar-xxl mx-auto mt-2">
                                            <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                                <img src={checkmark} alt="checkmark" height={64} width={64} />
                                            </div>
                                        </div>
                                    </div>

                                    <h4 className="fw-bold text-center mb-4">Well Done! Email verified Successfully</h4>

                                    <div className="d-grid">
                                        <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                            Back to Dashboard
                                        </Button>
                                    </div>
                                </Form>
                            </div>

                            <p className="text-muted text-center mt-4 mb-0">
                                Return to{' '}
                                <Link to="/auth-3/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                    Sign in
                                </Link>
                            </p>

                            <p className="text-center text-muted mt-auto mb-0">
                                © 2014 - <span>{currentYear}</span> INSPINIA — by{' '}
                                <span className="fw-semibold">{author}</span>
                            </p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </div>
    )
}

export default SuccessMail
