// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/login-pin/login-pin.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgOtpInputComponent } from 'ng-otp-input';

@Component({
    selector: 'app-login-pin',
    imports: [RouterLink,NgOtpInputComponent],
    templateUrl: './login-pin.component.html',
    styles: ``
})
export class LoginPinComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a routerLink="/" class="logo-dark">
                        <img src="assets/images/logo-black.png" alt="dark-logo" height="32"/>
                    </a>
                    <a routerLink="/" class="logo-light">
                        <img src="assets/images/logo.png" alt="logo" height="32"/>
                    </a>
                    <h4 class="fw-bold mt-3">Login with PIN! | IN+</h4>
                    <p class="text-muted w-lg-75 mx-auto">This screen is locked. Enter your PIN to continue.</p>
                </div>

                <div class="card p-4 rounded-4">
                    <div class="text-center mb-4">
                        <img src="assets/images/users/user-1.jpg" class="rounded-circle img-thumbnail avatar-xxl mb-2"
                            alt="thumbnail">
                        <h5 class="fs-md">Damian D.</h5>
                    </div>

                    <form>
                        <label class="form-label">Enter your 6-digit code <span class="text-danger">*</span></label>
                         <ng-otp-input
                                [config]="{ length: 6, allowNumbersOnly:true, inputClass:'form-control text-center',}">
                            </ng-otp-input>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Confirm</button>
                        </div>
                    </form>

                    <p class="text-muted text-center mt-4 mb-0">
                        Not you? Return to <a routerLink="/auth/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                    </p>
                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</div>

// src_old/views/auth/auth-1/login-pin/index.tsx

import { useState } from 'react';
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';

import { Link } from "react-router";;
import { Button, Card, Col, Container, Form, Row } from 'react-bootstrap';
import OTPInput from '@/components/OTPInput';

import user1 from '@/assets/images/users/user-1.jpg';

const LoginWithPin = () => {
    const [code, setCode] = useState<string[]>(Array(6).fill(''));
    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">
                            <AppLogo />
                            <h4 className="fw-bold mt-3">Login with PIN! | IN+</h4>
                            <p className="text-muted w-lg-75 mx-auto">
                                This screen is locked. Enter your PIN to continue.
                            </p>
                        </div>

                        <Card className="p-4 rounded-4">
                            <div className="text-center mb-4">
                                <img src={user1} alt="User thumbnail" className="rounded-circle img-thumbnail avatar-xxl mb-2" height={96}
                                />
                                <h5 className="fs-md">Damian D.</h5>
                            </div>

                            <Form>
                                <div className='form-group mb-3'>
                                    <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" />
                                </div>

                                <div className="d-grid">
                                    <Button type="submit" variant="primary" className="fw-semibold py-2">
                                        Confirm
                                    </Button>
                                </div>
                            </Form>

                            <p className="text-muted text-center mt-4 mb-0">
                                Not you? Return to{' '}
                                <Link
                                    to="/auth-1/sign-in"
                                    className="text-decoration-underline link-offset-3 fw-semibold"
                                >
                                    Sign in
                                </Link>
                            </p>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    );
};

export default LoginWithPin;
