// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/topbar/topbar.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterLink} from '@angular/router';
import {NgIcon} from '@ng-icons/core';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {LucideAngularModule, Search} from 'lucide-angular';

import {MegaMenuComponent} from '@layouts/components/topbar/components/mega-menu/mega-menu.component';
import {
    LanguageDropdownComponent
} from '@layouts/components/topbar/components/language-dropdown/language-dropdown.component';
import {
    MessagesDropdownComponent
} from '@layouts/components/topbar/components/messages-dropdown/messages-dropdown.component';
import {ThemeTogglerComponent} from '@layouts/components/topbar/components/theme-toggler/theme-toggler.component';
import {
    CustomizerTogglerComponent
} from '@layouts/components/topbar/components/customizer-toggler/customizer-toggler.component';
import {UserProfileComponent} from '@layouts/components/topbar/components/user-profile/user-profile.component';
import {
    NotificationDropdownComponent
} from '@layouts/components/topbar/components/notification-dropdown/notification-dropdown.component';

@Component({
    selector: 'app-topbar',
    imports: [
        CommonModule,
        NgIcon,
        RouterLink,
        LucideAngularModule,
        MegaMenuComponent,
        LanguageDropdownComponent,
        MessagesDropdownComponent,
        CustomizerTogglerComponent,
        ThemeTogglerComponent,
        UserProfileComponent,
        NotificationDropdownComponent,
    ],
    templateUrl: './topbar.component.html'
})
export class TopbarComponent {
    constructor(public layout: LayoutStoreService) {
    }

    toggleSidebar() {

        const html = document.documentElement;
        const currentSize = html.getAttribute('data-sidenav-size');
        const savedSize = this.layout.sidenavSize;

        if (currentSize === 'offcanvas') {
            html.classList.toggle('sidebar-enable')
            this.layout.showBackdrop()
        } else if (savedSize === 'compact') {
            this.layout.setSidenavSize(currentSize === 'compact' ? 'condensed' : 'compact', false);
        } else {
            this.layout.setSidenavSize(currentSize === 'condensed' ? 'default' : 'condensed');
        }
    }

    Search = Search;
}

<header class="app-topbar">
    <div class="container-fluid topbar-menu">
        <div class="d-flex align-items-center gap-2">
            <!-- Topbar Brand Logo -->
            <div class="logo-topbar">
                <!-- Logo light -->
                <a routerLink="/" class="logo-light">
                    <span class="logo-lg">
                      <img src="assets/images/logo.png" alt="logo">
                    </span>
                    <span class="logo-sm">
                        <img src="assets/images/logo-sm.png" alt="small logo">
                    </span>
                </a>

                <!-- Logo Dark -->
                <a routerLink="/" class="logo-dark">
                    <span class="logo-lg">
                      <img src="assets/images/logo-black.png" alt="dark logo">
                    </span>
                    <span class="logo-sm">
                      <img src="assets/images/logo-sm.png" alt="small logo">
                    </span>
                </a>
            </div>

            <!-- Sidebar Menu Toggle Button -->
            <button (click)="toggleSidebar()" class="sidenav-toggle-button btn btn-primary btn-icon">
                <ng-icon name="tablerMenu4" class="fs-22"/>
            </button>

            <!-- Search -->
            <div class="app-search d-none d-xl-flex">
                <input type="search" class="form-control topbar-search" name="search"
                       placeholder="Search for something...">
                <lucide-icon [img]="Search" class="app-search-icon text-muted"/>
            </div>

            <!-- Mega Menu Dropdown -->
            <app-mega-menu/>
        </div>

        <div class="d-flex align-items-center gap-2">
            <!-- Language Dropdown -->
            <app-language-dropdown/>

            <!-- Messages Dropdown -->
            <app-messages-dropdown/>

            <!-- Notification Dropdown -->
            <app-notification-dropdown/>

            <!-- Button Trigger Customizer Offcanvas -->
            <app-customizer-toggler/>

            <!-- Light/Dark Mode Button -->
            <app-theme-toggler/>

            <!-- User Dropdown -->
            <app-user-profile-topbar/>

        </div>
    </div>
</header>

// src/layouts/components/topbar/index.tsx


import {Button, Container} from "react-bootstrap";
// import MegaMenu from "@/layouts/components/topbar/components/MegaMenu";
// import LanguageDropdown from "@/layouts/components/topbar/components/LanguageDropdown";
// import MessageDropdown from "@/layouts/components/topbar/components/MessageDropdown";
import NotificationDropdown from "@/layouts/components/topbar/components/NotificationDropdown";
// import CustomizerToggler from "@/layouts/components/topbar/components/CustomizerToggler";
import ThemeToggler from "@/layouts/components/topbar/components/ThemeToggler";
import UserProfile from "@/layouts/components/topbar/components/UserProfile";
// import {LuSearch} from "react-icons/lu";
import {TbMenu4} from "react-icons/tb";
import {useLayoutContext} from "@/context/useLayoutContext";
import { Link } from "react-router";


import logo from "@/assets/images/logo.png"
import logoSm from "@/assets/images/logo-sm.png"
import logoDark from "@/assets/images/logo-black.png"

const Topbar = () => {

    const {sidenav, changeSideNavSize, showBackdrop} = useLayoutContext()

    const toggleSideNav = () => {
        const html = document.documentElement;
        const currentSize = html.getAttribute('data-sidenav-size');

        if (currentSize === 'offcanvas') {
            html.classList.toggle('sidebar-enable')
            showBackdrop()
        } else if (sidenav.size === 'compact') {
            changeSideNavSize(currentSize === 'compact' ? 'condensed' : 'compact', false);
        } else {
            changeSideNavSize(currentSize === 'condensed' ? 'default' : 'condensed');
        }
    }

    return (
        <header className="app-topbar">
            <Container fluid className="topbar-menu">
                <div className="d-flex align-items-center gap-2">

                    <div className="logo-topbar">
                        <Link to="/" className="logo-light">
                            <span className="logo-lg">
                                <img src={logo} alt="logo" width={92.3} height={26}/>
                            </span>
                            <span className="logo-sm">
                                <img src={logoSm} alt="small logo" width={30.55} height={26}/>
                            </span>
                        </Link>

                        <Link to="/" className="logo-dark">
                            <span className="logo-lg">
                                <img src={logoDark} alt="dark logo" width={92.3} height={26}/>
                            </span>
                            <span className="logo-sm">
                                <img src={logoSm} alt="small logo" width={30.55} height={26}/>
                            </span>
                        </Link>
                    </div>

                    <Button variant="primary" onClick={toggleSideNav} className="sidenav-toggle-button btn-icon">
                        <TbMenu4 className="fs-22"/>
                    </Button>

                    {/* <div className="app-search d-none d-xl-flex">
                        <FormControl type="search" className="topbar-search" name="search"
                                     placeholder="Search for something..."/>
                        <LuSearch className="app-search-icon text-muted"/>
                    </div> */}

                    {/* <MegaMenu/> */}
                </div>

                <div className="d-flex align-items-center gap-2">
                    {/* <LanguageDropdown/> */}

                    {/* <MessageDropdown/> */}

                    <NotificationDropdown/>

                    {/* <CustomizerToggler/> */}

                    <ThemeToggler/>

                    <UserProfile/>
                </div>
            </Container>
        </header>
    )
}

export default Topbar
