// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version3/delete-account/delete-account.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-delete-account',
    host: { 'data-component-id': 'auth3-delete-account' },
    imports: [RouterLink],
    templateUrl: './delete-account.component.html',
    styles: ``
})
export class DeleteAccountComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box p-0 w-100">
    <div class="row w-100 g-0">
        <div class="col">
            <div class="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                <div class="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                </div>
            </div>
        </div>

        <div class="col-xl-auto">
            <div class="card auth-box-form border-0 mb-0">
                <div class="card-body min-vh-100 d-flex flex-column justify-content-center">
                    <div class="auth-brand text-center">
                        <a routerLink="/" class="logo-dark">
                            <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a routerLink="/" class="logo-light">
                            <img src="assets/images/logo.png" alt="logo" height="32">
                        </a>
                    </div>

                    <div class="mt-auto text-center">
                        <div class="mb-4">
                            <div class="avatar-xxl mx-auto mt-2">
                                <div
                                    class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                    <img src="assets/images/delete.png" alt="dark logo" height="64">
                                </div>
                            </div>
                        </div>

                        <h4 class="fw-bold text-center mb-3">Account Deactivated</h4>
                        <p class="text-muted text-center mb-4">Your account is currently inactive. Reactivate now to
                            regain access to all features and opportunities.</p>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Reactivate Now</button>
                        </div>
                    </div>

                    <p class="text-center text-muted mt-auto mb-0">
                        © 2014 -
                        {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

// rawfiles/src/views/auth/auth-3/delete-account/index.tsx
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';

import { Button, Card, CardBody, Col, Row } from 'react-bootstrap';

import deleteIcon from '@/assets/images/delete.png';

const DeleteAccount = () => {
    return (
        <div className="auth-box p-0 w-100">
            <Row className="w-100 g-0">
                <Col>
                    <div className="h-100 position-relative card-side-img rounded-0 overflow-hidden">
                        <div className="p-4 card-img-overlay auth-overlay d-flex align-items-end justify-content-center">
                        </div>
                    </div>
                </Col>

                <Col xl="auto">
                    <Card className="auth-box-form border-0 mb-0">
                        <CardBody className="min-vh-100 d-flex flex-column justify-content-center">
                            <div className="auth-brand text-center">
                                <AppLogo />
                            </div>

                            <div className="mt-auto text-center">
                                <div className="mb-4">
                                    <div className="avatar-xxl mx-auto mt-2">
                                        <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                                            <img src={deleteIcon} alt="dark logo" height={64} width={64} />
                                        </div>
                                    </div>
                                </div>

                                <h4 className="fw-bold text-center mb-3">Account Deactivated</h4>
                                <p className="text-muted text-center mb-4">
                                    Your account is currently inactive. Reactivate now to regain access to all features and opportunities.
                                </p>

                                <div className="d-grid">
                                    <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                        Reactivate Now
                                    </Button>
                                </div>
                            </div>

                            <p className="text-center text-muted mt-auto mb-0">
                                © 2014 - {currentYear} INSPINIA — by{' '}
                                <span className="fw-semibold">{author}</span>
                            </p>
                        </CardBody>
                    </Card>
                </Col>
            </Row>
        </div>
    );
};

export default DeleteAccount;
