// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/landing/components/footer/footer.component.ts
import {credits, currentYear} from '@/app/constants';
import {CommonModule} from '@angular/common';
import {Component} from '@angular/core';
import {RouterLink} from '@angular/router';
import {NgIcon} from '@ng-icons/core';

type footerLinksType = {
    title: string;
    links: {
        name: string
        url: string;
        badge?: {
            title: string;
            variant: string
        }
    }[],
}

type socialLinksType = {
    title: string;
    icon: string;
    url: string
}

@Component({
    selector: 'app-footer',
    imports: [CommonModule, RouterLink, NgIcon],
    templateUrl: './footer.component.html',
    styles: ``
})
export class FooterComponent {
    currentYear = currentYear
    credits = credits
    socialLinks: socialLinksType[] = [
        {title: 'Facebook', icon: 'tablerBrandFacebook', url: '',},
        {title: 'Twitter-x', icon: 'tablerBrandX', url: '',},
        {title: 'Instagram', icon: 'tablerBrandInstagram', url: '',},
        {title: 'WhatsApp', icon: 'tablerBrandWhatsapp', url: '',},
    ];

    footerLinks: footerLinksType[] = [
        {
            title: 'Company',
            links: [
                {name: 'Our Story', url: ''},
                {name: 'Leadership Team', url: ''},
                {
                    name: 'Careers',
                    url: '',
                    badge: {title: "We're Hiring", variant: 'warning'}
                },
                {name: 'Press & Media', url: ''},
                {name: 'Investor Relations', url: ''},
                {name: 'Sustainability', url: ''},
            ],
        },
        {
            title: 'Community',
            links: [
                {name: 'Community Forum', url: ''},
                {name: 'Events & Meetups', url: ''},
                {name: 'Ambassadors', url: ''},
                {name: 'Customer Stories', url: ''},
                {name: 'Open Source', url: ''},
                {name: 'Code of Conduct', url: ''},
            ],
        },
        {
            title: 'Admin',
            links: [
                {name: 'Dashboard', url: ''},
                {name: 'User Management', url: ''},
                {name: 'Roles & Permissions', url: ''},
                {name: 'System Logs', url: ''},
                {name: 'Settings', url: ''},
                {name: 'API Access', url: ''},
            ],
        }
    ];
}

<footer class="section-custom section-footer pb-2">

    <div class="container">
        <div class="row g-4 justify-content-between">
            <div class="col-lg-3">
                <img src="assets/images/logo-white.png" alt="logo" height="30">
                <p class="mt-3 fs-sm">INSPINIA is the top-selling admin dashboard template on WrapBootstrap, known for
                    its sleek design, flexibility, and powerful features. Build modern web applications with ease using
                    the best in class!</p>

                <div class="d-flex gap-2 mt-4 mb-2">
                    <a *ngFor="let link of socialLinks" [routerLink]="link.url"
                        class="btn btn-sm btn-icon rounded-circle btn-dark" [attr.title]="link.title">
                        <ng-icon [name]="link.icon" class="fs-lg"/>
                    </a>
                </div>

            </div>

            <div class="col-lg-8 col-xxl-7">
                <div class="row g-4">
                    <div class="col-6 col-md-4" *ngFor="let section of footerLinks">
                        <h5 class="text-white mb-4 ps-2">{{ section.title }}</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item" *ngFor="let link of section.links">
                                <a class="nav-link" [class.pt-0]="section.links[0] === link" [routerLink]="link.url">
                                    {{ link.name }}
                                    <span *ngIf="link.badge" [class]="'badge text-bg-' + link.badge.variant"
                                        class="ms-2">
                                        {{ link.badge.title }}
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-12 text-center">
                <p class="mb-4">© 2014 -
                    {{currentYear}} Inspinia By <span class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</footer>

// src_old/views/landing/components/Footer.tsx
import { Col, Container, Row } from "react-bootstrap"

import logoWhite from '@/assets/images/logo-white.png'

import { Link } from "react-router";
import { author } from "@/helpers"
import type { footerLinksType, socialLinksType } from "./types"
import { LuDribbble, LuFacebook, LuInstagram } from "react-icons/lu"
import { TbBrandX } from "react-icons/tb"

const Footer = () => {
    const socialLinks: socialLinksType[] = [
        { title: 'Facebook', icon: LuFacebook, url: '', },
        { title: 'Twitter-x', icon: TbBrandX, url: '', },
        { title: 'Instagram', icon: LuInstagram, url: '', },
        { title: 'WhatsApp', icon: LuDribbble, url: '', },
    ];

    const footerLinks: footerLinksType[] = [
        {
            title: 'Company',
            links: [
                { name: 'Our Story', url: '' },
                { name: 'Leadership Team', url: '' },
                {
                    name: 'Careers',
                    url: '',
                    badge: { title: "We're Hiring", variant: 'warning' }
                },
                { name: 'Press & Media', url: '' },
                { name: 'Investor Relations', url: '' },
                { name: 'Sustainability', url: '' },
            ],
        },
        {
            title: 'Community',
            links: [
                { name: 'Community Forum', url: '' },
                { name: 'Events & Meetups', url: '' },
                { name: 'Ambassadors', url: '' },
                { name: 'Customer Stories', url: '' },
                { name: 'Open Source', url: '' },
                { name: 'Code of Conduct', url: '' },
            ],
        },
        {
            title: 'Admin',
            links: [
                { name: 'Dashboard', url: '' },
                { name: 'User Management', url: '' },
                { name: 'Roles & Permissions', url: '' },
                { name: 'System Logs', url: '' },
                { name: 'Settings', url: '' },
                { name: 'API Access', url: '' },
            ],
        }
    ];
    return (
        <footer className="section-custom section-footer pb-2">
            <Container>
                <Row className="g-4 justify-content-between">
                    <div className="col-lg-3">
                        <img src={logoWhite} alt="logo" height={30} />
                        <p className="mt-3 fs-sm">INSPINIA is the top-selling admin dashboard template on WrapBootstrap, known for its sleek design, flexibility, and powerful features. Build modern web applications with ease using the best in class!</p>
                        <div className="d-flex gap-2 mt-4 mb-2">
                            {socialLinks.map(({ icon: Icon, title, url }, idx) => (
                                <Link to={url} className="btn btn-sm btn-icon rounded-circle btn-dark" title={title} key={idx}>
                                    <Icon className="fs-sm" />
                                </Link>
                            ))}
                        </div>
                    </div>
                    <Col lg={8} xxl={7}>
                        <Row className="g-4">
                            {footerLinks.map((section, index) => (
                                <Col key={index} xs={6} md={4}>
                                    <h5 className="text-white mb-4 ps-2">{section.title}</h5>
                                    <ul className="nav flex-column">
                                        {section.links.map((link, i) => (
                                            <li className="nav-item" key={i}>
                                                    <Link to={link.url} className={`nav-link ${i === 0 && 'pt-0'}`}>
                                                        {link.name}
                                                        {link.badge && (
                                                            <span className={`ms-2 badge text-bg-${link.badge.variant}`}>
                                                                {link.badge.title}
                                                            </span>
                                                        )}
                                                    </Link>
                                            </li>
                                        ))}
                                    </ul>
                                </Col>
                            ))}
                        </Row>
                    </Col>
                </Row>
                <Row className="mt-5">
                    <Col xs={12} className="text-center">
                        <p className="mb-4">© 2014 -  Inspinia By <span className="fw-semibold">{author}</span> </p>
                    </Col>
                </Row>
            </Container>
        </footer>

    )
}

export default Footer
