// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/landing/components/testimonial-card/testimonial-card.component.ts
import { Component, Input } from '@angular/core';
import type { TestimonialType } from '../types';
import { CommonModule } from '@angular/common';
import {RatingComponent} from '@app/components/rating.component';

@Component({
    selector: 'app-testimonial-card',
    imports: [CommonModule, RatingComponent],
    templateUrl: './testimonial-card.component.html',
    styles: ``
})
export class TestimonialCardComponent {
    @Input() testimonial!: TestimonialType
}

<div class="card border-light rounded-4 p-3 card-h-100">
    <div class="card-body pb-0 text-center">
        <div class="avatar avatar-xl mx-auto mb-3">
            <img [src]="testimonial.avatar" [alt]="testimonial.name" class="img-fluid rounded-circle"/>
        </div>
        <span class="text-warning fs-lg mb-2 d-block">
          <app-rating [rate]="testimonial.rating" [readonly]="true" size="18"/>
        </span>
        <h4 class="mb-2 fs-md">{{ testimonial.title }}</h4>
        <p class="text-muted mb-3 fst-italic fs-sm">"{{ testimonial.description }}"</p>
    </div>
</div>

// src_old/views/landing/components/TestimonialCard.tsx

import { Card, CardBody } from "react-bootstrap"
import { TbStarFilled } from "react-icons/tb"
import type { TestimonialType } from "./types"

const TestimonialCard = ({ testimonial }: { testimonial: TestimonialType }) => {
    return (
        <Card className="card border-light rounded-4 p-3 card-h-100">
            <CardBody className="pb-0 text-center">
                <div className="avatar avatar-xl mx-auto mb-3">
                    <img
                        src={testimonial.avatar}
                        alt={testimonial.name}
                        className="img-fluid rounded-circle"
                    />
                </div>
                <span className="text-warning fs-lg mb-3 d-flex align-items-center justify-content-center gap-1">
                    {Array(5).fill(5).map((_star,idx) => (
                        <span key={idx}>
                            <TbStarFilled />
                        </span>
                    ))}
                </span>
                <h4 className="mb-2 fs-md">{testimonial.title}</h4>
                <p className="text-muted mb-3 fst-italic fs-sm">"{testimonial.description}"</p>
            </CardBody>
        </Card>
    )
}

export default TestimonialCard
