// rawfiles/src/views/auth/auth-1/sign-up/index.tsx

import AppLogo from '@/components/AppLogo'
import PasswordInputWithStrength from '@/components/PasswordInputWithStrength'
import { author, currentYear } from '@/helpers'
import { Link } from "react-router";
import { useState } from 'react'
import { Button, Card, Col, Container, Form, FormControl, FormLabel, Row } from 'react-bootstrap'

const SignUp = () => {
    const [password, setPassword] = useState('');
    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">
                            <AppLogo />
                            <h4 className="fw-bold mt-3">Register to IN+</h4>
                            <p className="text-muted w-lg-75 mx-auto">
                                Let’s get you started. Create your account by entering your details below.
                            </p>
                        </div>

                        <Card className="p-4 rounded-4">
                            <Form>
                                <div className="mb-3 form-group">
                                    <FormLabel>
                                        Name <span className="text-danger">*</span>
                                    </FormLabel>
                                    <FormControl type="text" placeholder="Damian D." required />
                                </div>

                                <div className="mb-3 form-group" >
                                    <FormLabel>
                                        Email address <span className="text-danger">*</span>
                                    </FormLabel>
                                    <FormControl type="email" placeholder="you@example.com" required />
                                </div>

                                <div className="mb-3">
                                    <PasswordInputWithStrength
                                        id='password'
                                        label='Password'
                                        name='password'
                                        password={password}
                                        setPassword={setPassword}
                                        placeholder='••••••••'
                                    />
                                </div>

                                <div className="mb-3">
                                    <div className="form-check">
                                        <input
                                            className="form-check-input form-check-input-light fs-14"
                                            type="checkbox"
                                            id="termAndPolicy"
                                        />
                                        <label className="form-check-label" htmlFor="termAndPolicy">
                                            Agree the Terms & Policy
                                        </label>
                                    </div>
                                </div>

                                <div className="d-grid">
                                    <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                        Create Account
                                    </Button>
                                </div>
                            </Form>

                            <p className="text-muted text-center mt-4 mb-0">
                                Already have an account?{' '}
                                <Link
                                    to="/auth-1/sign-in"
                                    className="text-decoration-underline link-offset-3 fw-semibold"
                                >
                                    Login
                                </Link>
                            </p>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default SignUp

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/sign-up/sign-up.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PasswordStrengthBarComponent } from "@app/components/password-strength-bar.component";

@Component({
    selector: 'app-sign-up',
    imports: [RouterLink, PasswordStrengthBarComponent,FormsModule],
    templateUrl: './sign-up.component.html',
    styles: ``
})
export class SignUpComponent {
    currentYear = currentYear
    credits = credits
    password: string = '';
}

<div class="auth-box overflow-hidden align-items-center d-flex">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xxl-4 col-md-6 col-sm-8">
                <div class="auth-brand text-center mb-4">
                    <a routerLink="/" class="logo-dark">
                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                    </a>
                    <a routerLink="/" class="logo-light">
                        <img src="assets/images/logo.png" alt="logo" height="32">
                    </a>
                    <h4 class="fw-bold mt-3">Register to IN+</h4>
                    <p class="text-muted w-lg-75 mx-auto">Let’s get you started. Create your account by entering your
                        details below.</p>
                </div>

                <div class="card p-4 rounded-4">
                    <form>
                        <div class="mb-3">
                            <label for="userName" class="form-label">Name <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="userName" placeholder="Damian D." required>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="userEmail" class="form-label">Email address <span
                                    class="text-danger">*</span></label>
                            <div class="input-group">
                                <input type="email" class="form-control" id="userEmail" placeholder="you@example.com"
                                    required>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="userPassword" class="form-label">Password <span
                                    class="text-danger">*</span></label>
                            <div class="input-group">
                                <input type="password" name="password" class="form-control" id="userPassword" placeholder="••••••••"
                                    required [(ngModel)]="password">
                            </div>
                            <app-password-strength-bar [password]="password" ></app-password-strength-bar>
                        </div>

                        <div class="mb-3">
                            <div class="form-check">
                                <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                    id="termAndPolicy">
                                <label class="form-check-label" for="termAndPolicy">Agree the Terms & Policy</label>
                            </div>
                        </div>

                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary fw-semibold py-2">Create Account</button>
                        </div>
                    </form>

                    <p class="text-muted text-center mt-4 mb-0">
                        Already have an account? <a routerLink="/auth/sign-in"
                            class="text-decoration-underline link-offset-3 fw-semibold">Login</a>
                    </p>
                </div>

                <p class="text-center text-muted mt-4 mb-0">
                    © 2014 -
                    {{currentYear}} INSPINIA — by <span
                        class="fw-semibold">{{credits.name}}</span>
                </p>
            </div>
        </div>
    </div>
</div>
