// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/footer/footer.component.ts
import {Component} from '@angular/core';
import {appName, credits, currentYear} from '@/app/constants';

@Component({
  selector: 'app-footer',
  imports: [],
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  currentYear = currentYear;
  appName = appName;
  credits = credits;
}

<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 text-center text-md-start">
        © 2014 - {{ currentYear }} {{ appName }} By <span class="fw-semibold">{{ credits.name }}</span>
      </div>
      <div class="col-md-6">
        <div class="text-md-end d-none d-md-block">
          10GB of <span class="fw-bold">250GB</span> Free.
        </div>
      </div>
    </div>
  </div>
</footer>

// src/layouts/components/footer/index.tsx
import {appName, author, currentYear} from "@/helpers";

const Footer = () => {
    return (
        <footer className="footer">
            <div className="container-fluid">
                <div className="row">
                    <div className="col-md-6 text-center text-md-start">
                        © 2014 - {currentYear} {appName} By <span
                        className="fw-semibold">{author}</span>
                    </div>
                    <div className="col-md-6">
                        <div className="text-md-end d-none d-md-block">
                            {/* 10GB of <span className="fw-bold">250GB</span> Free. */}
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    )
}

export default Footer
