// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/sign-up/sign-up.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgIcon } from '@ng-icons/core';
import { PasswordStrengthBarComponent } from "@app/components/password-strength-bar.component";
import { FormsModule } from '@angular/forms';

@Component({
    selector: 'app-sign-up',
    host: { 'data-component-id': 'auth2-sign-up' },
    imports: [RouterLink, NgIcon, PasswordStrengthBarComponent,FormsModule],
    templateUrl: './sign-up.component.html',
    styles: ``,
})
export class SignUpComponent {
    currentYear = currentYear
    credits = credits
     password: string = '';
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                    <h4 class="fw-bold mt-4">Register to IN+</h4>
                                    <p class="text-muted w-lg-75 mx-auto">Let’s get you started. Create your account by
                                        entering your details below.</p>
                                </div>

                                <form>
                                    <div class="mb-3">
                                        <label for="userName" class="form-label">Name <span
                                                class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <span class="input-group-text bg-light"><ng-icon name="tablerUser"
                                                    class="text-muted fs-xl" /></span>
                                            <input type="text" class="form-control" id="userName"
                                                placeholder="Damian D." required>
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <label for="userEmail" class="form-label">Email address <span
                                                class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <span class="input-group-text bg-light"><ng-icon name="tablerMail"
                                                    class="text-muted fs-xl" /></span>
                                            <input type="email" class="form-control" id="userEmail"
                                                placeholder="you@example.com" required>
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <label for="userPassword" class="form-label">Password <span
                                                class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <span class="input-group-text bg-light"><ng-icon name="tablerLockPassword"
                                                    class="ti ti-lock-password text-muted fs-xl" /></span>
                                            <input type="password" class="form-control" id="userPassword"
                                                placeholder="••••••••" required name="password" [(ngModel)]="password">
                                        </div>
                                        <app-password-strength-bar [password]="password" />
                                    </div>

                                    <div class="mb-3">
                                        <div class="form-check">
                                            <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                                checked id="termAndPolicy">
                                            <label class="form-check-label" for="termAndPolicy">Agree the Terms &
                                                Policy</label>
                                        </div>
                                    </div>

                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-primary fw-semibold py-2">Create
                                            Account</button>
                                    </div>
                                </form>

                                <p class="text-muted text-center mt-4 mb-0">
                                    Already have an account? <a routerLink="/auth-2/sign-in"
                                        class="text-decoration-underline link-offset-3 fw-semibold">Login</a>
                                </p>

                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// rawfiles/src/views/auth/auth-2/sign-up/index.tsx

import AppLogo from '@/components/AppLogo'
import PasswordInputWithStrength from '@/components/PasswordInputWithStrength'
import { author, currentYear } from '@/helpers'
import { Link } from "react-router";
import { useState } from 'react'
import { Button, Card, Col, Form, FormControl, FormLabel, Row } from 'react-bootstrap'
import { TbMail, TbUser } from 'react-icons/tb'


const SignUp = () => {
    const [password, setPassword] = useState('');

    return (
        <div className="auth-box d-flex align-items-center">
            <div className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <div className="card-body">
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                            <h4 className="fw-bold mt-4">Register to IN+</h4>
                                            <p className="text-muted w-lg-75 mx-auto">
                                                Let’s get you started. Create your account by entering your details below.
                                            </p>
                                        </div>

                                        <Form>
                                            <div className="mb-3">
                                                <FormLabel htmlFor="userName" className="form-label">
                                                    Name <span className="text-danger">*</span>
                                                </FormLabel>
                                                <div className="input-group">
                                                    <span className="input-group-text bg-light">
                                                        <TbUser className="text-muted fs-xl" />
                                                    </span>
                                                    <FormControl
                                                        type="text"
                                                        id="userName"
                                                        placeholder="Damian D."
                                                        required
                                                    />
                                                </div>
                                            </div>

                                            <div className="mb-3">
                                                <FormLabel htmlFor="userEmail" className="form-label">
                                                    Email address <span className="text-danger">*</span>
                                                </FormLabel>
                                                <div className="input-group">
                                                    <span className="input-group-text bg-light">
                                                        <TbMail className="text-muted fs-xl" />
                                                    </span>
                                                    <FormControl
                                                        type="email"
                                                        id="userEmail"
                                                        placeholder="you@example.com"
                                                        required
                                                    />
                                                </div>
                                            </div>

                                            <div className="mb-3" data-password="bar">
                                                <PasswordInputWithStrength
                                                    id='userPassword'
                                                    label='Password'
                                                    name='user-password'
                                                    password={password}
                                                    setPassword={setPassword}
                                                    placeholder='••••••••'
                                                    showIcon={true}
                                                />
                                            </div>

                                            <div className="mb-3">
                                                <div className="form-check">
                                                    <input className="form-check-input form-check-input-light fs-14" type="checkbox" defaultChecked id="termAndPolicy" />
                                                    <label className="form-check-label" htmlFor="termAndPolicy">Agree the Terms &amp; Policy</label>
                                                </div>
                                            </div>

                                            <div className="d-grid">
                                                <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                                    Create Account
                                                </Button>
                                            </div>
                                        </Form>

                                        <p className="text-muted text-center mt-4 mb-0">
                                            Already have an account?{' '}
                                            <Link
                                                to="/auth-2/sign-in"
                                                className="text-decoration-underline link-offset-3 fw-semibold"
                                            >
                                                Login
                                            </Link>
                                        </p>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by{' '}
                                            <span className="fw-semibold">{author}</span>
                                        </p>
                                    </div>
                                </Col>

                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </div>
        </div>
    )
}

export default SignUp
