// src/layouts/components/topbar/components/UserProfile.tsx
// import {Link} from "react-router";
import { useNavigate, Link } from 'react-router-dom';
import {Fragment} from "react";
import {Dropdown, DropdownDivider, DropdownItem, DropdownMenu, DropdownToggle} from "react-bootstrap";
import {userDropdownItems} from "@/layouts/components/data";
import {TbChevronDown} from "react-icons/tb";
import { capitalizeWords } from '@/utils/stringUtils'; // adjust path if needed
import { getUserInfo } from '@/utils/auth';
import user2 from "@/assets/images/users/user-2.jpg"
import Cookies from 'js-cookie';
const UserProfile = () => {
     const navigate = useNavigate();
     const UserInfo = getUserInfo();
    const handleLogout = () => {
  // Clear cookies or any other stored auth data
  Cookies.remove('accessToken');
  Cookies.remove('LeadHubLoginAccess');

  // Redirect to login
  navigate('/login');
};
    return (
        <div className="topbar-item nav-user">
            <Dropdown align="end">
                <DropdownToggle as={'a'} className="topbar-link dropdown-toggle drop-arrow-none px-2">
                    <img src={user2} width="32" height="32" className="rounded-circle me-lg-2 d-flex"
                         alt="user-image"/>
                    <div className="d-lg-flex align-items-center gap-1 d-none">
                        <h5 className="my-0">{UserInfo?.full_name ? capitalizeWords(UserInfo.full_name) : ''}</h5>
                        <TbChevronDown className="align-middle"/>
                    </div>
                </DropdownToggle>
                {/* <DropdownMenu className="dropdown-menu-end">
                    {
                        userDropdownItems.map((item, idx) => (
                            <Fragment key={idx}>
                                {
                                    item.isHeader ?
                                        <div className="dropdown-header noti-title">
                                            <h6 className="text-overflow m-0">{item.label}</h6>
                                        </div> :
                                        item.isDivider ? <DropdownDivider/> :
                                            <DropdownItem as={Link} to={item.url ?? '#'} className={item.class}>
                                                {
                                                    item.icon &&
                                                    <item.icon className="me-2 fs-17 align-middle"/>
                                                }
                                                <span className="align-middle">{item.label}</span>
                                            </DropdownItem>
                                }
                            </Fragment>
                        ))
                    }
                </DropdownMenu> */}
                <DropdownMenu className="dropdown-menu-end">
  {userDropdownItems.map((item, idx) => (
    <Fragment key={idx}>
      {item.isHeader ? (
        <div className="dropdown-header noti-title">
          <h6 className="text-overflow m-0">{capitalizeWords(item.label || '')}</h6>
        </div>
      ) : item.isDivider ? (
        <DropdownDivider />
      ) : (
        <DropdownItem
          as={item.isLogout ? 'button' : Link}
          // to={item.url ?? '#'}
          className={item.class}
          onClick={item.isLogout ? handleLogout : undefined}
        >
          {item.icon && <item.icon className="me-2 fs-17 align-middle" />}
          <span className="align-middle">{capitalizeWords(item.label || '')}</span>
        </DropdownItem>
      )}
    </Fragment>
  ))}
</DropdownMenu>


            </Dropdown>
        </div>
    )
}

export default UserProfile;

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/topbar/components/user-profile/user-profile.component.ts
import {Component} from '@angular/core';
import {CommonModule} from "@angular/common";
import {NgbDropdown, NgbDropdownMenu, NgbDropdownToggle} from "@ng-bootstrap/ng-bootstrap";
import {userDropdownItems} from '@layouts/components/data';
import {RouterLink} from '@angular/router';
import {NgIcon} from '@ng-icons/core';

@Component({
  selector: 'app-user-profile-topbar',
  imports: [
    CommonModule,
    NgbDropdown,
    NgbDropdownMenu,
    NgbDropdownToggle,
    RouterLink,
    NgIcon
  ],
  templateUrl: './user-profile.component.html'
})
export class UserProfileComponent {
  menuItems = userDropdownItems;
}

<div class="topbar-item nav-user">
    <div ngbDropdown [placement]="'bottom-end'" class="dropdown">
        <button ngbDropdownToggle class="btn btn-link p-0 topbar-link dropdown-toggle drop-arrow-none px-2">
            <img src="assets/images/users/user-2.jpg" width="32" class="rounded-circle me-lg-2 d-flex"
                 alt="user-image">
            <div class="d-lg-flex align-items-center gap-1 d-none">
                <h5 class="my-0">Damian D.</h5>
                <span class="d-flex align-middle"><ng-icon name="tablerChevronDown"/></span>
            </div>
        </button>
        <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
            <div *ngFor="let item of menuItems">
                <div *ngIf="item.isHeader" class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">{{ item.label }}</h6>
                </div>

                <div *ngIf="item.isDivider" class="dropdown-divider"></div>

                <a *ngIf="!item.isHeader && !item.isDivider && item.url" [routerLink]="item.url" class="dropdown-item"
                   [ngClass]="item.class">
                    <ng-icon [name]="item.icon" size="17" class="align-middle d-inline-flex align-items-center me-2"/>
                    <span class="align-middle" [innerHTML]="item.label"></span>
                </a>
            </div>
        </div>

    </div>
</div>
