// src/layouts/components/navbar/components/AppMenu.tsx
import type {MenuItemType} from "@/types/layout";
import {Dropdown, DropdownMenu, DropdownToggle} from "react-bootstrap";
import {Fragment} from "react";
import {Link, useLocation} from "react-router";
import {horizontalMenuItems} from "@/layouts/components/data";
import {TbChevronDown} from "react-icons/tb";



const MenuItemWithChildren = ({item, wrapperClass, togglerClass, level}: {
    item: MenuItemType,
    wrapperClass?: string,
    togglerClass?: string,
    level?: number,
}) => {

    const menuLevel = level ?? 1
    const {pathname} = useLocation();

    const isChildActive = (items: MenuItemType[]): boolean =>
        items.some(child => {
            if (child.url && pathname.endsWith(child.url)) return true;
            if (child.children) return isChildActive(child.children);
            return false;
        });

    const isActive = isChildActive(item.children || []);

    return (
        <Dropdown as={menuLevel > 1 ? 'div' : 'li'} drop={menuLevel > 1 ? 'end' : 'down'}
                  className={`${wrapperClass ?? ''} ${isActive ? 'active' : ''}`}>
            <DropdownToggle as={'a'} className={`${togglerClass} dropdown-toggle drop-arrow-none ${isActive ? 'active' : ''}`}>
                {item.icon && <span className="menu-icon"><item.icon/></span>}
                <span className="menu-text"> {item.label} </span>
                {!item.badge && <div className="menu-arrow"><TbChevronDown/></div>}
            </DropdownToggle>
            <DropdownMenu>
                {
                    (item.children || []).map((child, idx) => (
                        <Fragment key={idx}>
                            {
                                child.children ?
                                    <MenuItemWithChildren item={child} togglerClass="dropdown-item"
                                                          level={menuLevel + 1}/> :
                                    <MenuItem item={child} linkClass="dropdown-item" level={menuLevel + 1}/>
                            }
                        </Fragment>
                    ))
                }
            </DropdownMenu>
        </Dropdown>
    )
}

const MenuItem = ({item, linkClass, wrapperClass, level}: {
    item: MenuItemType,
    linkClass?: string,
    wrapperClass?: string,
    level?: number,
}) => {

    const menuLevel = level ?? 1
    const {pathname} = useLocation();
    const isActive = item.url && pathname.endsWith(item.url);

    const link = (
        <Link to={item.url ?? '/'} className={`${linkClass ?? ''} ${isActive ? 'active' : ''}`}>
            {item.icon && <span className="menu-icon"><item.icon/></span>}
            <span className="menu-text">{item.label}</span>
            {item.badge && (
                <span className={`badge text-bg-${item.badge.variant} opacity-50`}>
                      {item.badge.text}
                </span>
            )}
        </Link>
    );

    return menuLevel > 1 ? link : <li className={`${wrapperClass ?? ''} ${isActive ? 'active' : ''}`}>{link}</li>
}


const AppMenu = () => {
    return (
        <div className="collapse navbar-collapse">
            <ul className="navbar-nav">
                {
                    horizontalMenuItems.map((item, idx) => (
                        <Fragment key={idx}>
                            {
                                item.children ? <MenuItemWithChildren item={item} wrapperClass="nav-item"
                                                                      togglerClass="nav-link"/> :
                                    <MenuItem item={item} linkClass="nav-link" wrapperClass="nav-item"/>
                            }
                        </Fragment>
                    ))
                }
            </ul>
        </div>
    )
}

export default AppMenu

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/navbar/components/app-menu/app-menu.component.ts
import {Component, TemplateRef, ViewChild} from '@angular/core';
import {MenuItemType} from '@/app/types/layout';
import {CommonModule} from '@angular/common';
import {NgIcon} from '@ng-icons/core';
import {NgbDropdown, NgbDropdownMenu, NgbDropdownToggle} from '@ng-bootstrap/ng-bootstrap';
import {NavigationEnd, Router, RouterLink} from '@angular/router';
import {horizontalMenuItems} from '@layouts/components/data';
import {filter} from 'rxjs';

@Component({
    selector: 'app-menu-navbar',
    imports: [
        CommonModule,
        NgIcon,
        NgbDropdown,
        NgbDropdownToggle,
        RouterLink,
        NgbDropdownMenu
    ],
    templateUrl: './app-menu.component.html'
})
export class AppMenuComponent {

    constructor(public router: Router) {
    }

    @ViewChild('MenuItemWithChildren', {static: true})
    menuItemWithChildren!: TemplateRef<{ item: MenuItemType, wrapperClass?: string, togglerClass?: string }>;

    @ViewChild('MenuItem', {static: true})
    menuItem!: TemplateRef<{ item: MenuItemType, linkClass?: string }>;

    menuItems = horizontalMenuItems;

    hasSubMenu(item: MenuItemType): boolean {
        return !!item.children;
    }

    isChildActive(item: MenuItemType): boolean {
        if (item.url && this.router.url === item.url) return true;
        if (!item.children) return false;
        return item.children.some((child: any) => this.isChildActive(child));
    }

    isActive(item: MenuItemType): boolean {
        return item.url === this.router.url;
    }
}

<div class="collapse navbar-collapse" id="topnav-menu-content">
    <ul class="navbar-nav">
        <ng-container *ngFor="let item of menuItems">

            <!-- menu item without any child -->
            <ng-container *ngIf="!hasSubMenu(item)">
                <li class="nav-item">
                    <ng-container *ngTemplateOutlet="MenuItem;context:{item,linkClass:'nav-link'}"/>
                </li>
            </ng-container>

            <!-- menu item with child -->
            <ng-container *ngIf="hasSubMenu(item)">
                <ng-container
                    *ngTemplateOutlet="MenuItemWithChildren;context:{item, wrapperClass:'nav-item', togglerClass:'nav-link'}"/>
            </ng-container>

        </ng-container>
    </ul>
</div>

<ng-template #MenuItemWithChildren let-item="item" let-wrapperClass="wrapperClass" let-togglerClass="togglerClass">
    <li ngbDropdown [class]="wrapperClass" class="dropdown" [ngClass]="{'active': isChildActive(item)}">
        <a ngbDropdownToggle [class]="togglerClass" class="dropdown-toggle drop-arrow-none" role="button">
            <span *ngIf="item.icon">
                <ng-icon class="menu-icon" [name]="item.icon"></ng-icon>
            </span>
            <span class="menu-text"> {{ item.label }} </span>
            <span *ngIf="item.badge" [class]="`badge bg-${item.badge.variant}`">{{ item.badge.text }}</span>
            <span *ngIf="!item.badge" class="menu-arrow">
                <ng-icon name="tablerChevronDown"></ng-icon>
             </span>
        </a>
        <div ngbDropdownMenu class="dropdown-menu">
            <ng-container *ngFor="let child of item.children">
                <!-- menu item without any child -->
                <ng-container *ngIf="!hasSubMenu(child)">
                    <ng-container *ngTemplateOutlet="MenuItem;context:{item:child,linkClass:'dropdown-item'}"/>
                </ng-container>

                <!-- menu item with child -->
                <ng-container *ngIf="hasSubMenu(child)">
                    <ng-container
                        *ngTemplateOutlet="MenuItemWithChildren;context:{item:child,togglerClass:'dropdown-item'}"/>
                </ng-container>
            </ng-container>
        </div>
    </li>
</ng-template>

<ng-template #MenuItem let-item="item" let-linkClass="linkClass">
    <a *ngIf="item.url" [routerLink]="item.url" [target]="item.target" [class]="linkClass" [class.active]="isActive(item)"
       [ngClass]="{'disabled': item.isDisabled,'special-menu': item.isSpecial}">
      <span *ngIf="item.icon">
        <ng-icon class="menu-icon" [name]="item.icon"></ng-icon>
      </span>
        <span class="menu-text">{{ item.label }}</span>
        <span *ngIf="item.badge" [ngClass]="`badge text-bg-${item.badge.variant} opacity-50`"
              [innerHTML]="item.badge.text"></span>
    </a>
</ng-template>
