// files/INSPINIA_v4.2.0/React/Seed/src/views/auth/auth-1/lock-screen/index.tsx
import { Button, Card, Col, Container, Form, FormControl, FormLabel, Row } from "react-bootstrap"

import { author, currentYear } from "@/helpers"
import avatar from '@/assets/images/users/user-1.jpg'

import { Link } from "react-router";

const LockScreen = () => {
    return (
        <div className="auth-box overflow-hidden align-items-center d-flex">
            <Container>
                <Row className="justify-content-center">
                    <Col xxl={4} md={6} sm={8}>
                        <div className="auth-brand text-center mb-4">

                            <h4 className="fw-bold mt-3">Lock Screen! | IN+</h4>
                            <p className="text-muted w-lg-75 mx-auto">
                                This screen is locked. Enter your password to continue
                            </p>
                        </div>

                        <Card className="p-4 rounded-4">
                            <div className="text-center mb-4">
                                <img
                                    src={avatar}
                                    className="rounded-circle img-thumbnail avatar-xxl mb-2"
                                    alt="thumbnail"
                                />
                                <h5 className="fs-md">Damian D.</h5>
                            </div>

                            <Form>
                                <div className="mb-3">
                                    <FormLabel htmlFor="userPassword">
                                        Password <span className="text-danger">*</span>
                                    </FormLabel>
                                    <div className="input-group">
                                        <FormControl
                                            type="password"
                                            id="userPassword"
                                            placeholder="••••••••"
                                            required
                                        />
                                    </div>
                                </div>

                                <div className="d-grid">
                                    <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                        Unlock
                                    </Button>
                                </div>
                            </Form>

                            <p className="text-muted text-center mt-4 mb-0">
                                Not you? Return to{' '}
                                <Link to="/auth-1/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                                    Sign in
                                </Link>
                            </p>
                        </Card>

                        <p className="text-center text-muted mt-4 mb-0">
                            © 2014 - {currentYear} INSPINIA — by{' '}
                            <span className="fw-semibold">{author}</span>
                        </p>
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default LockScreen

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version1/lock-screen/lock-screen.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-lock-screen',
    imports: [RouterLink],
    templateUrl: './lock-screen.component.html',
    styles: ``
})
export class LockScreenComponent {
    currentYear = currentYear
    credits = credits
}

    <div class="auth-box overflow-hidden align-items-center d-flex">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xxl-4 col-md-6 col-sm-8">
                    <div class="auth-brand text-center mb-4">
                        <a routerLink="/" class="logo-dark">
                            <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                        </a>
                        <a routerLink="/" class="logo-light">
                            <img src="assets/images/logo.png" alt="logo" height="32">
                        </a>
                        <h4 class="fw-bold mt-3">Lock Screen! | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">This screen is locked. Enter your password to continue</p>
                    </div>

                    <div class="card p-4 rounded-4">
                        <div class="text-center mb-4">
                            <img src="assets/images/users/user-1.jpg" class="rounded-circle img-thumbnail avatar-xxl mb-2" alt="thumbnail">
                            <h5 class="fs-md">Damian D.</h5>
                        </div>

                        <form>

                            <div class="mb-3">
                                <label for="userPassword" class="form-label">Password <span class="text-danger">*</span></label>
                                <div class="input-group">
                                    <input type="password" class="form-control" id="userPassword" placeholder="••••••••" required>
                                </div>
                            </div>

                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary fw-semibold py-2">Unlock</button>
                            </div>
                        </form>

                        <p class="text-muted text-center mt-4 mb-0">
                            Not you? Return to <a routerLink="/auth/sign-in" class="text-decoration-underline link-offset-3 fw-semibold">Sign in</a>
                        </p>
                    </div>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 -
                        {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
