// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/sidenav/sidenav.component.ts
import {Component} from '@angular/core';
import {UserProfileComponent} from '@layouts/components/sidenav/components/user-profile/user-profile.component';
import {AppMenuComponent} from '@layouts/components/sidenav/components/app-menu/app-menu.component';
import {SimplebarAngularModule} from 'simplebar-angular';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {NgIf} from '@angular/common';
import {NgIcon} from '@ng-icons/core';
import {RouterLink} from '@angular/router';

@Component({
  selector: 'app-sidenav',
    imports: [
        UserProfileComponent,
        AppMenuComponent,
        SimplebarAngularModule,
        NgIf,
        NgIcon,
        RouterLink
    ],
  templateUrl: './sidenav.component.html',
})
export class SidenavComponent {
  constructor(public layout: LayoutStoreService) {
  }

  hoverSidebar() {
    this.layout.setSidenavSize(this.layout.sidenavSize === 'on-hover-active' ? 'on-hover' : 'on-hover-active')
  }

  closeSidebar() {
    const html = document.documentElement;
    html.classList.toggle('sidebar-enable')
    this.layout.hideBackdrop()
  }
}

<div class="sidenav-menu">

    <a routerLink="/" class="logo">
        <span class="logo logo-light">
          <span class="logo-lg"><img src="assets/images/logo.png" alt="logo"></span>
          <span class="logo-sm"><img src="assets/images/logo-sm.png" alt="small logo"></span>
        </span>

        <span class="logo logo-dark">
          <span class="logo-lg"><img src="assets/images/logo-black.png" alt="dark logo"></span>
          <span class="logo-sm"><img src="assets/images/logo-sm.png" alt="small logo"></span>
        </span>
    </a>

    <!-- Sidebar Hover Menu Toggle Button -->
    <button (click)="hoverSidebar()" class="button-on-hover">
        <ng-icon name="tablerMenu4" size="22" class="align-middle"/>
    </button>

    <!-- Offcanvas Sidebar Menu Close Button -->
    <button (click)="closeSidebar()" class="button-close-offcanvas">
        <ng-icon name="tablerX" class="align-middle"/>
    </button>

    <ngx-simplebar id="sidenav" class="scrollbar">
        <!-- User -->
        <app-user-profile *ngIf="layout.sidenavUser"/>

        <!--- Sidenav Menu -->
        <app-menu/>
    </ngx-simplebar>
</div>

// rawfiles/src/layouts/components/sidenav/index.tsx

import SimpleBar from 'simplebar-react';
import UserProfile from "@/layouts/components/sidenav/components/UserProfile";
import AppMenu from "@/layouts/components/sidenav/components/AppMenu";
import {useLayoutContext} from "@/context/useLayoutContext";
import {TbMenu4, TbX} from "react-icons/tb";
import { Link } from "react-router";

import logo from "@/assets/images/logo.png";
import logoSm from "@/assets/images/logo-sm.png";
import logoDark from "@/assets/images/logo-black.png";


const Sidenav = () => {

    const {sidenav, hideBackdrop, changeSideNavSize} = useLayoutContext()

    const toggleSidebar = () => {
        changeSideNavSize(sidenav.size === 'on-hover-active' ? 'on-hover' : 'on-hover-active')
    }

    const closeSidebar = () => {
        const html = document.documentElement;
        html.classList.toggle('sidebar-enable')
        hideBackdrop()
    }

    return (
        <div className="sidenav-menu">

            <Link to="/" className="logo">
                <span className="logo logo-light">
                    <span className="logo-lg"><img src={logo} alt="logo" width={92.3} height={26}/></span>
                    <span className="logo-sm"><img src={logoSm} alt="small logo" width={30.55} height={26}/></span>
                </span>

                <span className="logo logo-dark">
                    <span className="logo-lg"><img src={logoDark} alt="dark logo" width={92.3} height={26}/></span>
                    <span className="logo-sm"><img src={logoSm} alt="small logo" width={30.55} height={26}/></span>
                </span>
            </Link>

            <button className="button-on-hover">
                <TbMenu4 onClick={toggleSidebar} className="ti ti-menu-4 fs-22 align-middle"/>
            </button>

            <button className="button-close-offcanvas">
                <TbX onClick={closeSidebar} className="align-middle"/>
            </button>

            <SimpleBar id="sidenav" className="scrollbar">
                {
                    sidenav.user && <UserProfile/>
                }
                <AppMenu/>
            </SimpleBar>
        </div>
    );
}

export default Sidenav
