// files/INSPINIA_v4.2.0/Angular/Seed/src/app/layouts/components/topbar/components/theme-toggler/theme-toggler.component.ts
import {Component} from '@angular/core';
import {LayoutStoreService} from '@core/services/layout-store.service';
import {LucideAngularModule, Moon, Sun} from 'lucide-angular';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'app-theme-toggler',
  imports: [LucideAngularModule, CommonModule],
  templateUrl: './theme-toggler.component.html'
})
export class ThemeTogglerComponent {

  constructor(public layout: LayoutStoreService) {
  }

  readonly Moon = Moon;
  readonly Sun = Sun;

  toggleTheme() {
    if (this.layout.theme === 'light') {
      this.layout.setTheme('dark')
    } else {
      this.layout.setTheme('light')
    }
  }
}

<div class="topbar-item d-none d-sm-flex">
  <button (click)="toggleTheme()" class="topbar-link" type="button">
    <lucide-icon [img]="Moon" *ngIf="layout.theme === 'light'" class="fs-xxl mode-light-moon"/>
    <lucide-icon [img]="Sun" *ngIf="layout.theme === 'dark'" class="fs-xxl mode-light-sun"/>
  </button>
</div>

// files/INSPINIA_v4.2.0/React/Seed/src/layouts/components/topbar/components/ThemeToggler.tsx

import {useEffect, useState} from "react";
import {LuMoon, LuSun} from "react-icons/lu";

import {useLayoutContext} from "@/context/useLayoutContext";

const ThemeToggler = () => {

    const {theme, changeTheme} = useLayoutContext()

    const toggleTheme = () => {
        if (theme === "dark") {
            changeTheme('light')
            return;
        }
        changeTheme('dark');
        return;
    }

    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    if (!mounted) return null;

    return (
        <div className="topbar-item d-none d-sm-flex">
            <button onClick={toggleTheme} className="topbar-link" type="button">
                {
                    theme === "dark" ?
                        <LuSun className="fs-xxl mode-light-sun"/> :
                        <LuMoon className="fs-xxl mode-light-moon"/>
                }
            </button>
        </div>
    )
}

export default ThemeToggler;
