// src/views/auth/auth-2/sign-in/index.tsx
import { Button, Card, Col, Form, FormControl, FormLabel, Row } from "react-bootstrap"
import { author, currentYear } from "@/helpers"

import { Link } from "react-router";
import AppLogo from "@/components/AppLogo"
import { TbLockPassword, TbMail } from "react-icons/tb"

const SignIn = () => {
    return (
        <div className="auth-box d-flex align-items-center">
            <div className="container-xxl">
                <Row className="align-items-center justify-content-center">
                    <Col xl={10}>
                        <Card className="rounded-4">
                            <Row className="justify-content-between g-0">
                                <Col lg={6}>
                                    <div className="card-body">
                                        <div className="auth-brand text-center mb-4">
                                            <AppLogo />
                                            <h4 className="fw-bold mt-4">Welcome to IN+</h4>
                                            <p className="text-muted w-lg-75 mx-auto">
                                                Let’s get you signed in. Enter your email and password to continue.
                                            </p>
                                        </div>

                                        <Form>
                                            <div className="mb-3">
                                                <FormLabel htmlFor="userEmail" className="form-label">
                                                    Email address <span className="text-danger">*</span>
                                                </FormLabel>
                                                <div className="input-group">
                                                    <span className="input-group-text bg-light">
                                                        <TbMail  className="text-muted fs-xl" />
                                                    </span>
                                                    <FormControl
                                                        type="email"
                                                        id="userEmail"
                                                        placeholder="you@example.com"
                                                        required
                                                    />
                                                </div>
                                            </div>

                                            <div className="mb-3">
                                                <FormLabel htmlFor="userPassword" className="form-label">
                                                    Password <span className="text-danger">*</span>
                                                </FormLabel>
                                                <div className="input-group">
                                                    <span className="input-group-text bg-light">
                                                        <TbLockPassword  className="text-muted fs-xl" />
                                                    </span>
                                                    <FormControl
                                                        type="password"
                                                        id="userPassword"
                                                        placeholder="••••••••"
                                                        required
                                                    />
                                                </div>
                                            </div>

                                            <div className="d-flex justify-content-between align-items-center mb-3">
                                                <div className="form-check">
                                                    <input className="form-check-input form-check-input-light fs-14" type="checkbox" id="rememberMe" />
                                                    <label className="form-check-label" htmlFor="rememberMe">Keep me signed in</label>
                                                </div>

                                                <Link
                                                    to="/auth-2/reset-password"
                                                    className="text-decoration-underline link-offset-3 text-muted"
                                                >
                                                    Forgot Password?
                                                </Link>
                                            </div>

                                            <div className="d-grid">
                                                <Button type="submit" className="btn btn-primary fw-semibold py-2">
                                                    Sign In
                                                </Button>
                                            </div>
                                        </Form>

                                        <p className="text-muted text-center mt-4 mb-0">
                                            New here?{' '}
                                            <Link
                                                to="/auth-2/sign-up"
                                                className="text-decoration-underline link-offset-3 fw-semibold"
                                            >
                                                Create an account
                                            </Link>
                                        </p>

                                        <p className="text-center text-muted mt-4 mb-0">
                                            © 2014 - {currentYear} INSPINIA — by{' '}
                                            <span className="fw-semibold">{author}</span>
                                        </p>
                                    </div>
                                </Col>
                                <Col lg={6} className="d-none d-lg-block">
                                    <div className="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                        <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                                    </div>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
            </div>
        </div>
    )
}

export default SignIn

// files/INSPINIA_v4.2.0/Angular/Seed/src/app/pages/auth/version2/sign-in/sign-in.component.ts
import { credits, currentYear } from '@/app/constants';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgIcon } from '@ng-icons/core';

@Component({
    selector: 'app-sign-in',
    host: { 'data-component-id': 'auth2-sign-in' },
    imports: [RouterLink,NgIcon],
    templateUrl: './sign-in.component.html',
    styles: ``,
})
export class SignInComponent {
    currentYear = currentYear
    credits = credits
}

<div class="auth-box d-flex align-items-center">
    <div class="container-xxl">
        <div class="row align-items-center justify-content-center">
            <div class="col-xl-10">
                <div class="card rounded-4">
                    <div class="row justify-content-between g-0">
                        <div class="col-lg-6">
                            <div class="card-body">
                                <div class="auth-brand text-center mb-4">
                                    <a routerLink="/" class="logo-dark">
                                        <img src="assets/images/logo-black.png" alt="dark logo" height="32">
                                    </a>
                                    <a routerLink="/" class="logo-light">
                                        <img src="assets/images/logo.png" alt="logo" height="32">
                                    </a>
                                    <h4 class="fw-bold mt-4">Welcome to IN+</h4>
                                    <p class="text-muted w-lg-75 mx-auto">Let’s get you signed in. Enter your email and
                                        password to continue.</p>
                                </div>

                                <form>
                                    <div class="mb-3">
                                        <label for="userEmail" class="form-label">Email address <span
                                                class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <span class="input-group-text bg-light"><ng-icon name="tablerMail"
                                                    class="text-muted fs-xl" /></span>
                                            <input type="email" class="form-control" id="userEmail"
                                                placeholder="you@example.com" required>
                                        </div>
                                    </div>

                                    <div class="mb-3">
                                        <label for="userPassword" class="form-label">Password <span
                                                class="text-danger">*</span></label>
                                        <div class="input-group">
                                            <span class="input-group-text bg-light"><ng-icon
                                                    name="tablerLockPassword" class="text-muted fs-xl" /></span>
                                            <input type="password" class="form-control" id="userPassword"
                                                placeholder="••••••••" required>
                                        </div>
                                    </div>

                                    <div class="d-flex justify-content-between align-items-center mb-3">
                                        <div class="form-check">
                                            <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                                id="rememberMe">
                                            <label class="form-check-label" for="rememberMe">Keep me signed in</label>
                                        </div>
                                        <a routerLink="/auth-2/reset-pw"
                                            class="text-decoration-underline link-offset-3 text-muted">Forgot
                                            Password?</a>
                                    </div>

                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-primary fw-semibold py-2">Sign In</button>
                                    </div>
                                </form>

                                <p class="text-muted text-center mt-4 mb-0">
                                    New here? <a routerLink="/auth-2/sign-up"
                                        class="text-decoration-underline link-offset-3 fw-semibold">Create an
                                        account</a>
                                </p>

                                <p class="text-center text-muted mt-4 mb-0">
                                    © 2014 -
                                    {{currentYear}} INSPINIA — by <span class="fw-semibold">{{credits.name}}</span>
                                </p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-none d-lg-block">
                            <div
                                class="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                                <div
                                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
